import {expect} from 'chai';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import {discoverConfigs} from '../src/cli';
import {stackGenerate} from '../src/cli';

describe('CLI configuration discovery', () => {
	it('discovers units and stacks in stable relative order', async () => {
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclp-cli-'));
		await fs.mkdir(path.join(root, 'z', '.hidden'), {recursive: true});
		await fs.mkdir(path.join(root, 'a'), {recursive: true});
		await fs.writeFile(path.join(root, 'z', 'terragrunt.stack.hcl'), 'unit "app" { source = "." path = "app" }');
		await fs.writeFile(path.join(root, 'a', 'terragrunt.hcl'), 'inputs = {}');
		await fs.writeFile(path.join(root, 'z', '.hidden', 'terragrunt.hcl'), 'inputs = {}');

		const visible = await discoverConfigs(root, true);
		expect(visible.map(config => [config.type, config.path])).to.deep.equal([
			['unit', 'a'],
			['stack', 'z']
		]);

		const all = await discoverConfigs(root, false);
		expect(all.map(config => config.path)).to.deep.equal(['a', 'z', 'z/.hidden']);
		await fs.rm(root, {recursive: true, force: true});
	});

	it('generates a local stack component and evaluated values file', async () => {
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclp-stack-'));
		await fs.mkdir(path.join(root, 'modules', 'app'), {recursive: true});
		await fs.writeFile(path.join(root, 'modules', 'app', 'terragrunt.hcl'), 'inputs = { from = "source" }\n');
		await fs.writeFile(path.join(root, 'terragrunt.stack.hcl'), [
			'unit "app" {',
			'  source = "./modules/app"',
			'  path = "generated/app"',
			'  values = { region = "eu" replicas = 2 }',
			'}',
			''
		].join('\n'));
		const result = await stackGenerate(['--working-dir', root]);
		expect(result).to.equal(0);
		expect(await fs.readFile(path.join(root, '.terragrunt-stack', 'generated', 'app', 'terragrunt.hcl'), 'utf8')).to.equal('inputs = { from = "source" }\n');
		expect(await fs.readFile(path.join(root, '.terragrunt-stack', 'generated', 'app', 'terragrunt.values.hcl'), 'utf8')).to.equal('# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually\nregion   = "eu"\nreplicas = 2\n');
		await fs.rm(root, {recursive: true, force: true});
	});
});
