import {expect} from 'chai';
import fs from 'node:fs/promises';
import fsSync from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import {discoverConfigs} from '../src/cli';
import {stackGenerate} from '../src/cli';
import {spawn, spawnSync} from 'node:child_process';
import {createServer} from 'node:http';

describe('CLI configuration discovery', function () {
	this.timeout(10000);
	it('discovers units and stacks in stable relative order', async () => {
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclp-cli-'));
		await fs.mkdir(path.join(root, 'z', '.hidden'), {recursive: true});
		await fs.mkdir(path.join(root, 'a'), {recursive: true});
		await fs.writeFile(path.join(root, 'z', 'terragrunt.stack.hcl'), 'unit "app" { source = "." path = "app" }');
		await fs.writeFile(path.join(root, 'a', 'terragrunt.hcl'), 'inputs = {}');
		await fs.writeFile(path.join(root, 'z', '.hidden', 'terragrunt.hcl'), 'inputs = {}');

		const visible = await discoverConfigs(root, true);
		expect(visible.map(config => [config.type, config.path])).to.deep.equal([
			['unit', 'a'],
			['stack', 'z']
		]);

		const all = await discoverConfigs(root, false);
		expect(all.map(config => config.path)).to.deep.equal(['a', 'z', 'z/.hidden']);
		await fs.rm(root, {recursive: true, force: true});
	});

	it('generates a local stack component and evaluated values file', async () => {
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclp-stack-'));
		await fs.mkdir(path.join(root, 'modules', 'app'), {recursive: true});
		await fs.writeFile(path.join(root, 'modules', 'app', 'terragrunt.hcl'), 'inputs = { from = "source" }\n');
		await fs.writeFile(path.join(root, 'terragrunt.stack.hcl'), [
			'unit "app" {',
			'  source = "./modules/app"',
			'  path = "generated/app"',
			'  values = { region = "eu" replicas = 2 }',
			'}',
			''
		].join('\n'));
		const result = await stackGenerate(['--working-dir', root]);
		expect(result).to.equal(0);
		expect(await fs.readFile(path.join(root, '.terragrunt-stack', 'generated', 'app', 'terragrunt.hcl'), 'utf8')).to.equal('inputs = { from = "source" }\n');
		expect(await fs.readFile(path.join(root, '.terragrunt-stack', 'generated', 'app', 'terragrunt.values.hcl'), 'utf8')).to.equal('# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually\nregion   = "eu"\nreplicas = 2\n');
		await fs.rm(root, {recursive: true, force: true});
	});

	it('runs and cleans the generated stack lifecycle', async () => {
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclp-stack-lifecycle-'));
		await fs.mkdir(path.join(root, 'module'), {recursive: true});
		await fs.writeFile(path.join(root, 'module', 'terragrunt.hcl'), 'inputs = {}\n');
		await fs.writeFile(path.join(root, 'terragrunt.stack.hcl'), 'unit "app" { source = "./module" path = "generated/app" }\n');
		const cli = path.resolve('dist/cli.cjs');
		const run = spawnSync(process.execPath, [cli, 'stack', 'run', '--working-dir', root, '--tf-path', '/bin/echo', 'plan'], {encoding: 'utf8'});
		expect(run.status).to.equal(0, run.stderr);
		expect(run.stdout).to.equal('Generated unit app\nplan\n');
		const generatedStat = await fs.stat(path.join(root, '.terragrunt-stack', 'generated', 'app', 'terragrunt.hcl'));
		expect(generatedStat.isFile()).to.equal(true);
		const clean = spawnSync(process.execPath, [cli, 'stack', 'clean', '--working-dir', root], {encoding: 'utf8'});
		expect(clean.status).to.equal(0, clean.stderr);
		let exists = true;
		try { await fs.access(path.join(root, '.terragrunt-stack')); } catch { exists = false; }
		expect(exists).to.equal(false);
		await fs.rm(root, {recursive: true, force: true});
	});

	it('generates a stack from a Git source repository', async function () {
		this.timeout(10000);
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclp-stack-git-'));
		const repository = path.join(root, 'repository');
		await fs.mkdir(path.join(repository, 'module'), {recursive: true});
		await fs.writeFile(path.join(repository, 'module', 'terragrunt.hcl'), 'inputs = {}\n');
		for (const args of [['init', '-q'], ['config', 'user.email', 'test@example.invalid'], ['config', 'user.name', 'tghclp-test'], ['add', '.'], ['commit', '-qm', 'fixture']]) {
			const result = spawnSync('git', args, {cwd: repository, encoding: 'utf8', shell: false});
			expect(result.status).to.equal(0, result.stderr);
		}
		await fs.writeFile(path.join(root, 'terragrunt.stack.hcl'), `unit "app" { source = "git::file://${repository}//module" path = "generated/app" }\n`);
		const cli = path.resolve('dist/cli.cjs');
		const result = spawnSync(process.execPath, [cli, 'stack', 'generate', '--working-dir', root], {encoding: 'utf8'});
		expect(result.status).to.equal(0, result.stderr);
		expect(await fs.readFile(path.join(root, '.terragrunt-stack', 'generated', 'app', 'terragrunt.hcl'), 'utf8')).to.equal('inputs = {}\n');
		await fs.rm(root, {recursive: true, force: true});
	});

	it('renders JSON configuration without dropping the authored structure', async () => {
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclp-render-json-'));
		await fs.writeFile(path.join(root, 'terragrunt.hcl.json'), JSON.stringify({inputs: {region: 'eu-west-1'}, terraform: {source: './module'}}));
		const cli = path.resolve('dist/cli.cjs');
		const result = spawnSync(process.execPath, [cli, 'render', '--json', '--working-dir', root, '--config', 'terragrunt.hcl.json'], {encoding: 'utf8'});
		expect(result.status).to.equal(0, result.stderr);
		expect(JSON.parse(result.stdout)).to.deep.equal({inputs: {region: 'eu-west-1'}, terraform: {source: './module'}});
		await fs.rm(root, {recursive: true, force: true});
	});

	it('scaffolds a local module without unresolved placeholders', async () => {
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclp-scaffold-'));
		const moduleDir = path.join(root, 'module');
		const outputDir = path.join(root, 'generated');
		await fs.mkdir(moduleDir, {recursive: true});
		await fs.writeFile(path.join(moduleDir, 'variables.tf'), [
			'variable "region" {',
			'  description = "Deployment region"',
			'  default = "eu-west-1"',
			'}',
			'variable "name" {',
			'  description = "Service name"',
			'}',
			''
		].join('\n'));
		const cli = path.resolve('dist/cli.cjs');
		const result = spawnSync(process.execPath, [cli, 'scaffold', './module', '--working-dir', root, '--output-folder', 'generated', '--var', 'name=api', '--no-include-root'], {encoding: 'utf8'});
		expect(result.status).to.equal(0, result.stderr);
		expect(await fs.readFile(path.join(outputDir, 'terragrunt.hcl'), 'utf8')).to.equal([
			'terraform {',
			'  source = "./module"',
			'}',
			'',
			'inputs = {',
			'  name = "api"',
			'  region = "eu-west-1"',
			'}',
			''
		].join('\n'));
		await fs.rm(root, {recursive: true, force: true});
	});

	it('rejects unsafe scaffold boundaries and unknown execution options', async function () {
		this.timeout(10000);
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclp-cli-boundary-'));
		const outside = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclp-cli-outside-'));
		await fs.writeFile(path.join(outside, 'variables.tf'), 'variable "region" { default = "eu-west-1" }\n');
		const inside = path.join(root, 'module');
		await fs.mkdir(inside, {recursive: true});
		await fs.writeFile(path.join(inside, 'variables.tf'), 'variable "region" { default = "eu-west-1" }\n');
		const cli = path.resolve('dist/cli.cjs');
		const sourceEscape = spawnSync(process.execPath, [cli, 'scaffold', `../${path.basename(outside)}`, '--working-dir', root, '--output-folder', 'generated'], {encoding: 'utf8'});
		expect(sourceEscape.status).to.not.equal(0);
		expect(sourceEscape.stderr).to.contain('inside the working directory');
		const outputEscape = spawnSync(process.execPath, [cli, 'scaffold', './module', '--working-dir', root, '--output-folder', '../generated'], {encoding: 'utf8'});
		expect(outputEscape.status).to.not.equal(0);
		expect(outputEscape.stderr).to.contain('inside the working directory');
		const unknown = spawnSync(process.execPath, [cli, 'hcl', 'format', '--definitely-unknown', '--working-dir', root], {encoding: 'utf8'});
		expect(unknown.status).to.not.equal(0);
		expect(unknown.stderr).to.contain('Unknown format option');
		await fs.rm(root, {recursive: true, force: true});
		await fs.rm(outside, {recursive: true, force: true});
	});

	it('scaffolds a Git module source and selects its subdirectory', async () => {
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclp-scaffold-git-'));
		const repository = path.join(root, 'repository');
		await fs.mkdir(path.join(repository, 'modules', 'app'), {recursive: true});
		await fs.writeFile(path.join(repository, 'modules', 'app', 'variables.tf'), 'variable "region" { default = "eu-west-1" }\n');
		for (const args of [['init', '-q'], ['config', 'user.email', 'test@example.invalid'], ['config', 'user.name', 'tghclp-test'], ['add', '.'], ['commit', '-qm', 'fixture']]) {
			const result = spawnSync('git', args, {cwd: repository, encoding: 'utf8', shell: false});
			expect(result.status).to.equal(0, result.stderr);
		}
		const output = path.join(root, 'generated');
		const cli = path.resolve('dist/cli.cjs');
		const source = `git::file://${repository}//modules/app`;
		const result = spawnSync(process.execPath, [cli, 'scaffold', source, '--working-dir', root, '--output-folder', 'generated', '--no-include-root'], {encoding: 'utf8'});
		expect(result.status).to.equal(0, result.stderr);
		expect(await fs.readFile(path.join(output, 'terragrunt.hcl'), 'utf8')).to.contain(`source = ${JSON.stringify(source)}`);
		expect(await fs.readFile(path.join(output, 'terragrunt.hcl'), 'utf8')).to.contain('region = "eu-west-1"');
		await fs.rm(root, {recursive: true, force: true});
	});

	it('scaffolds an HTTP archive module source and selects its subdirectory', async function () {
		this.timeout(10000);
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclp-scaffold-archive-'));
		const repository = path.join(root, 'repository');
		await fs.mkdir(path.join(repository, 'module'), {recursive: true});
		await fs.writeFile(path.join(repository, 'module', 'variables.tf'), 'variable "region" { default = "eu-west-1" }\n');
		const archive = path.join(root, 'module.zip');
		const zipped = spawnSync('zip', ['-qr', archive, '.'], {cwd: repository, encoding: 'utf8', shell: false});
		expect(zipped.status).to.equal(0, zipped.stderr);
		const server = createServer((_, response) => fsSync.createReadStream(archive).pipe(response));
		await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve));
		try {
			const address = server.address();
			if (address === null || typeof address === 'string') throw new Error('archive test server did not expose a TCP port');
			const source = `http://127.0.0.1:${address.port}/module.zip//module`;
			const output = path.join(root, 'generated');
			const cli = path.resolve('dist/cli.cjs');
			const result = await new Promise<{status: number | null; stdout: string; stderr: string}>((resolve, reject) => {
				const child = spawn(process.execPath, [cli, 'scaffold', source, '--working-dir', root, '--output-folder', 'generated', '--no-include-root'], {encoding: 'utf8'});
				let stdout = '';
				let stderr = '';
				child.stdout.on('data', chunk => { stdout += String(chunk); });
				child.stderr.on('data', chunk => { stderr += String(chunk); });
				child.on('error', reject);
				child.on('close', status => resolve({status, stdout, stderr}));
			});
			expect(result.status).to.equal(0, result.stderr);
			expect(await fs.readFile(path.join(output, 'terragrunt.hcl'), 'utf8')).to.contain('region = "eu-west-1"');
		} finally {
			await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve()));
			await fs.rm(root, {recursive: true, force: true});
		}
	});

	it('scaffolds a Mercurial module source through the configured hg executable', async () => {
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclp-scaffold-hg-'));
		const repository = path.join(root, 'repository');
		const bin = path.join(root, 'bin');
		await fs.mkdir(path.join(repository, 'module'), {recursive: true});
		await fs.mkdir(bin, {recursive: true});
		await fs.writeFile(path.join(repository, 'module', 'variables.tf'), 'variable "region" { default = "eu-west-1" }\n');
		await fs.writeFile(path.join(bin, 'hg'), '#!/usr/bin/env node\nconst fs=require("node:fs"); const args=process.argv.slice(2); fs.cpSync(args[args.length-2], args[args.length-1], {recursive:true});\n', {mode: 0o755});
		const cli = path.resolve('dist/cli.cjs');
		const source = `hg::${repository}//module?ref=stable`;
		const result = spawnSync(process.execPath, [cli, 'scaffold', source, '--working-dir', root, '--output-folder', 'generated', '--no-include-root'], {encoding: 'utf8', env: {...process.env, PATH: `${bin}${path.delimiter}${process.env.PATH ?? ''}`}});
		expect(result.status).to.equal(0, result.stderr);
		expect(await fs.readFile(path.join(root, 'generated', 'terragrunt.hcl'), 'utf8')).to.contain('region = "eu-west-1"');
		await fs.rm(root, {recursive: true, force: true});
	});

	it('lists local catalog components as JSON lines only with the catalog experiment', async function () {
		this.timeout(10000);
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclp-catalog-'));
		const catalog = path.join(root, 'catalog');
		const component = path.join(catalog, 'network');
		await fs.mkdir(component, {recursive: true});
		await fs.writeFile(path.join(root, 'terragrunt.hcl'), 'catalog { urls = ["./catalog"] }\n');
		await fs.writeFile(path.join(component, 'terragrunt.hcl'), 'terraform { source = "./module" }\n');
		const cli = path.resolve('dist/cli.cjs');
		const rejected = spawnSync(process.execPath, [cli, 'catalog', '--format=jsonl', '--working-dir', root], {encoding: 'utf8'});
		expect(rejected.status).to.not.equal(0);
		const result = spawnSync(process.execPath, [cli, 'catalog', '--format=jsonl', '--experiment=catalog-format', '--working-dir', root], {encoding: 'utf8'});
		expect(result.status).to.equal(0, result.stderr);
		expect(JSON.parse(result.stdout)).to.deep.equal({kind: 'unit', title: 'network', description: '', source: './catalog', dir: 'network', component_source: './module', copyable: true});
		await fs.rm(root, {recursive: true, force: true});
	});

	it('lists components from a Git catalog source', async () => {
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclp-catalog-git-'));
		const repository = path.join(root, 'repository');
		await fs.mkdir(path.join(repository, 'modules', 'network'), {recursive: true});
		await fs.writeFile(path.join(repository, 'modules', 'network', 'terragrunt.hcl'), 'terraform { source = "./network" }\n');
		for (const args of [['init', '-q'], ['config', 'user.email', 'test@example.invalid'], ['config', 'user.name', 'tghclp-test'], ['add', '.'], ['commit', '-qm', 'fixture']]) {
			const result = spawnSync('git', args, {cwd: repository, encoding: 'utf8', shell: false});
			expect(result.status).to.equal(0, result.stderr);
		}
		await fs.writeFile(path.join(root, 'terragrunt.hcl'), `catalog { urls = ["git::file://${repository}"] }\n`);
		const cli = path.resolve('dist/cli.cjs');
		const result = spawnSync(process.execPath, [cli, 'catalog', '--format=jsonl', '--experiment=catalog-format', '--working-dir', root], {encoding: 'utf8'});
		expect(result.status).to.equal(0, result.stderr);
		expect(JSON.parse(result.stdout)).to.deep.include({kind: 'unit', title: 'network', component_source: './network', copyable: true});
		await fs.rm(root, {recursive: true, force: true});
	});

	it('runs all units in dependency order', async () => {
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclp-run-all-'));
		await fs.mkdir(path.join(root, 'app'), {recursive: true});
		await fs.mkdir(path.join(root, 'database'), {recursive: true});
		await fs.writeFile(path.join(root, 'app', 'terragrunt.hcl'), 'dependency "database" { config_path = "../database" }\ninputs = {}\n');
		await fs.writeFile(path.join(root, 'database', 'terragrunt.hcl'), 'inputs = {}\n');
		const cli = path.resolve('dist/cli.cjs');
		const result = spawnSync(process.execPath, [cli, 'run', '--all', '--tf-path', '/bin/echo', '--working-dir', root, 'plan'], {encoding: 'utf8'});
		expect(result.status).to.equal(0, result.stderr);
		expect(result.stdout).to.equal('plan\nplan\n');
		await fs.rm(root, {recursive: true, force: true});
	});

	it('performs local backend bootstrap and forced state deletion', async () => {
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclp-backend-'));
		await fs.writeFile(path.join(root, 'terragrunt.hcl'), 'remote_state { backend = "local" config = { path = "state.tfstate" } }\n');
		await fs.writeFile(path.join(root, 'state.tfstate'), '{}\n');
		const cli = path.resolve('dist/cli.cjs');
		const bootstrap = spawnSync(process.execPath, [cli, 'backend', 'bootstrap', '--tf-path', '/bin/echo', '--working-dir', root], {encoding: 'utf8'});
		expect(bootstrap.status).to.equal(0, bootstrap.stderr);
		expect(bootstrap.stderr).to.contain('Bootstrap for local backend not implemented.');
		const deleted = spawnSync(process.execPath, [cli, 'backend', 'delete', '--force', '--working-dir', root], {encoding: 'utf8'});
		expect(deleted.status).to.equal(0, deleted.stderr);
		let stateExists = true;
		try { await fs.access(path.join(root, 'state.tfstate')); } catch { stateExists = false; }
		expect(stateExists).to.equal(true);
		await fs.rm(root, {recursive: true, force: true});
	});

	it('performs S3 backend bootstrap and state deletion through provider operations', async function () {
		this.timeout(10000);
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclp-backend-s3-'));
		const bin = path.join(root, 'bin');
		await fs.mkdir(bin, {recursive: true});
		const log = path.join(root, 'provider.log');
		const provider = path.join(bin, 'aws');
		await fs.writeFile(provider, `#!/usr/bin/env node\nconst fs=require('node:fs'); const args=process.argv.slice(2); fs.appendFileSync(${JSON.stringify(log)}, args.join(' ')+'\\n'); if ((args[0]==='s3api' && args[1]==='head-bucket') || (args[0]==='dynamodb' && args[1]==='describe-table')) process.exit(1);\n`, {mode: 0o755});
		await fs.writeFile(path.join(root, 'terragrunt.hcl'), 'remote_state { backend = "s3" config = { bucket = "state" key = "env/app.tfstate" region = "eu-west-1" dynamodb_table = "locks" } }\n');
		const cli = path.resolve('dist/cli.cjs');
		const environment = {...process.env, PATH: `${bin}${path.delimiter}${process.env.PATH ?? ''}`};
		const bootstrap = spawnSync(process.execPath, [cli, 'backend', 'bootstrap', '--working-dir', root], {encoding: 'utf8', env: environment});
		expect(bootstrap.status).to.equal(0, bootstrap.stderr);
		const deleted = spawnSync(process.execPath, [cli, 'backend', 'delete', '--force', '--working-dir', root], {encoding: 'utf8', env: environment});
		expect(deleted.status).to.equal(0, deleted.stderr);
		const commands = (await fs.readFile(log, 'utf8')).trim().split('\n');
		expect(commands).to.deep.equal([
			's3api head-bucket --bucket state',
			's3api create-bucket --bucket state --create-bucket-configuration LocationConstraint=eu-west-1',
			's3api put-bucket-versioning --bucket state --versioning-configuration Status=Enabled',
			'dynamodb describe-table --table-name locks',
			'dynamodb create-table --table-name locks --attribute-definitions AttributeName=LockID,AttributeType=S --key-schema AttributeName=LockID,KeyType=HASH --billing-mode PAY_PER_REQUEST',
			'dynamodb delete-item --table-name locks --key LockID={S=state/env/app.tfstate-md5}',
			's3api delete-object --bucket state --key env/app.tfstate'
		]);
		await fs.rm(root, {recursive: true, force: true});
	});

	it('runs lifecycle hooks around the selected IaC command', async () => {
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclp-hooks-'));
		await fs.writeFile(path.join(root, 'terragrunt.hcl'), [
			'terraform {',
			'  before_hook "before" { commands = ["plan"] execute = ["/bin/echo", "before"] }',
			'  after_hook "after" { commands = ["plan"] execute = ["/bin/echo", "after"] }',
			'}',
			'inputs = {}',
			''
		].join('\n'));
		const cli = path.resolve('dist/cli.cjs');
		const result = spawnSync(process.execPath, [cli, 'run', '--tf-path', '/bin/echo', '--working-dir', root, 'plan'], {encoding: 'utf8'});
		expect(result.status).to.equal(0, result.stderr);
		expect(result.stdout).to.equal('before\nplan\nafter\n');
		await fs.rm(root, {recursive: true, force: true});
	});

	it('signs generated files and refuses to overwrite ones it did not write', async () => {
		// `if_exists = "overwrite_terragrunt"` asks to overwrite a file THIS
		// tool generated, not whatever happens to share the name. The signature
		// line is how that is known, and without it a generate block would
		// destroy a hand-written file silently.
		//
		// The signature is deliberately not terragrunt's: each tool refuses a
		// file bearing the other's mark, so a directory generated into by one
		// is not quietly taken over by the other. Verified against terragrunt
		// 0.67.1, which refuses a tghclparser-signed file in exactly this way.
		const cli = path.resolve('dist/cli.cjs');
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclparser-sig-'));
		await fs.mkdir(path.join(root, '.git'));
		await fs.writeFile(path.join(root, 'terragrunt.hcl'), [
			'generate "g" {',
			'  path      = "out.tf"',
			'  if_exists = "overwrite_terragrunt"',
			'  contents  = "locals { a = 1 }"',
			'}'
		].join('\n'));
		const unit = path.join(root, 'unit');
		await fs.mkdir(unit);
		await fs.writeFile(
			path.join(unit, 'terragrunt.hcl'),
			'include "root" {\n  path = find_in_parent_folders("terragrunt.hcl")\n}\n'
		);
		const target = path.join(unit, 'out.tf');
		const args = [cli, 'init', '--working-dir', unit, '--tf-path', '/bin/echo'];

		// Generation happens before tofu runs, so what matters is the file
		// written, not the stub binary's exit status.
		spawnSync(process.execPath, args, {cwd: unit, encoding: 'utf8'});
		const written = await fs.readFile(target, 'utf8');
		expect(written.split('\n')[0]).to.match(/^# Generated by tghclparser\. Sig: /u);
		expect(written).to.contain('locals { a = 1 }');

		// Its own file is overwritten, which is what the setting asks for.
		const second = spawnSync(process.execPath, args, {cwd: unit, encoding: 'utf8'});
		expect(`${second.stdout}${second.stderr}`).to.not.contain('not generated by tghclparser');

		// A file it did not write is left exactly as it was found.
		await fs.writeFile(target, '# written by hand\n');
		const refused = spawnSync(process.execPath, args, {cwd: unit, encoding: 'utf8'});
		expect(`${refused.stdout}${refused.stderr}`).to.contain('not generated by tghclparser');
		expect(await fs.readFile(target, 'utf8')).to.equal('# written by hand\n');

		// Including one terragrunt itself generated.
		await fs.writeFile(target, '# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa\nlocals {}\n');
		const foreign = spawnSync(process.execPath, args, {cwd: unit, encoding: 'utf8'});
		expect(`${foreign.stdout}${foreign.stderr}`).to.contain('not generated by tghclparser');
		expect(await fs.readFile(target, 'utf8')).to.contain('Generated by Terragrunt');

		await fs.rm(root, {recursive: true, force: true});
	});

	it('runs when invoked under the name npm links it as', async () => {
		// `npm install -g` links `bin/tghclp` at dist/cli.js, so argv[1] is that
		// bin path rather than a filename ending in `/cli.js`. A check for the
		// filename was false for every globally installed copy: the command
		// exited 0, printed nothing and did nothing, which reads as a program
		// with no output rather than one that never started.
		const cli = path.resolve('dist/cli.cjs');
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclparser-bin-'));
		const link = path.join(root, 'tghclp');
		await fs.symlink(cli, link);
		const result = spawnSync(process.execPath, [link, '--help'], {encoding: 'utf8'});
		expect(result.status).to.equal(0, result.stderr);
		expect(result.stdout).to.contain('Usage: tghclp');
		await fs.rm(root, {recursive: true, force: true});
	});

	it('accepts the legacy --terragrunt- spellings of flags it honours, and no others', async () => {
		// Terragrunt renamed these when it dropped the prefix, and scripts still
		// pass the old names -- one deployment here has twenty-one occurrences
		// of `--terragrunt-non-interactive`. Refusing them would make swapping
		// the executable a rewrite of every caller.
		//
		// Only flags actually honoured are aliased. A legacy flag accepted and
		// then ignored is worse than one refused: the caller believes it took
		// effect.
		const cli = path.resolve('dist/cli.cjs');
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tghclparser-legacy-'));
		await fs.writeFile(path.join(root, 'terragrunt.hcl'), 'locals { x = 1 }\n');
		const run = (flag: string) => spawnSync(
			process.execPath, [cli, 'hcl', 'validate', '--working-dir', root, flag], {encoding: 'utf8'}
		);

		for (const flag of [
			'--non-interactive', '--terragrunt-non-interactive',
			'--no-color', '--terragrunt-no-color',
			'--no-tips', '--terragrunt-no-tips'
		]) {
			const result = run(flag);
			expect(`${result.stdout}${result.stderr}`).to.not.contain('Unknown option', flag);
		}

		// A legacy flag with no equivalent here is still refused, rather than
		// accepted and quietly dropped.
		for (const flag of ['--terragrunt-download-dir', '--terragrunt-debug', '--terragrunt-nonsense']) {
			const result = run(flag);
			expect(`${result.stdout}${result.stderr}`).to.contain('Unknown option', flag);
		}

		await fs.rm(root, {recursive: true, force: true});
	});
});
