#!/usr/bin/env node

import fs from 'node:fs/promises';
import fsSync from 'node:fs';
import {spawnSync} from 'node:child_process';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { ConfigEvaluator, runtimeValueToPlain } from './Evaluator';
import { convertToRuntimeValue, makeObjectValue } from './functions/utils';
import type { RuntimeValue, ValueType } from './model';
import type { FunctionDefinition } from './model';
import { ParsedDocument } from './ParsedDocument';
import { Workspace } from './Workspace';
import { parse } from './parser';

interface CLIOptions {
	json: boolean;
	showConfigPath: boolean;
	experiments: string[];
	workingDir: string;
	paths: string[];
	format?: 'text' | 'json' | 'tree' | 'dot';
	noHidden: boolean;
	dependencies: boolean;
	dag: boolean;
}

/**
 * Directories outside the workspace root that `--allow-path` opened up.
 *
 * Module-level because every evaluator this file builds needs it and there
 * are ten of them; threading a parameter through each would make the ones
 * that forgot it fail in a way that looks like the boundary working.
 */
const allowedPaths: string[] = [];

/**
 * The first line of every file a `generate` block writes.
 *
 * A marker, not a hash: it says the file is this tool's to overwrite, which is
 * what `if_exists = "overwrite_terragrunt"` actually asks about. Without it a
 * generate block would overwrite anything sharing the name, including a file
 * somebody wrote by hand.
 *
 * The signature is deliberately NOT terragrunt's. The two tools each refuse a
 * file bearing the other's mark, so a directory that has been generated into
 * by one is not silently taken over by the other -- and the message names
 * which tool wrote what.
 */
const GENERATED_SIGNATURE = '# Generated by tghclparser. Sig: 8fJqR2mTvX4nLpZw';

/**
 * Flags that change presentation or prompting and carry no value.
 *
 * Each is accepted under its `--terragrunt-` spelling as well. Terragrunt
 * renamed these when it dropped the prefix, and a great many scripts still
 * pass the old names -- twenty-one occurrences of
 * `--terragrunt-non-interactive` in one deployment here. Refusing them makes
 * substituting this executable a rewrite of every caller, which is the
 * opposite of a drop-in replacement.
 *
 * Only flags this actually honours are aliased. A legacy flag accepted and
 * then ignored would be worse than one refused: the caller would believe it
 * had taken effect.
 */
const PASSTHROUGH_FLAGS = new Set(['--no-cas', '--no-color', '--no-tips', '--non-interactive']);

/** Whether an argument is one of those, under either spelling. */
function isPassthroughFlag(argument: string): boolean {
	if (PASSTHROUGH_FLAGS.has(argument)) return true;
	return argument.startsWith('--terragrunt-')
		&& PASSTHROUGH_FLAGS.has(`--${argument.slice('--terragrunt-'.length)}`);
}

const tofuShortcuts = new Set(['apply', 'destroy', 'force-unlock', 'import', 'init', 'output', 'plan', 'refresh', 'show', 'state', 'test', 'validate']);

interface DiagnosticOutput {
	range: {
		filename: string;
		start: { line: number; column: number; byte: number };
		end: { line: number; column: number; byte: number };
	};
	summary: string;
	detail: string;
	severity: 'error';
}

const fileNames = new Set([
	'terragrunt.hcl',
	'terragrunt.hcl.json',
	'terragrunt.stack.hcl',
	'terragrunt.stack.hcl.json',
	'terragrunt.values.hcl',
	'terragrunt.autoinclude.hcl',
	'terragrunt.autoinclude.stack.hcl'
]);

function validateJSONShape(value: unknown, fileName: string): void {
	if (value === null || typeof value !== 'object' || Array.isArray(value)) {
		throw new Error('JSON configuration must be an object');
	}
	if (fileName === 'terragrunt.values.hcl.json') return;
	const stack = fileName === 'terragrunt.stack.hcl.json';
	const allowed = stack
		? new Set(['unit', 'stack', 'include', 'locals', 'feature', 'exclude', 'errors', 'autoinclude'])
		: new Set(['inputs', 'terraform', 'remote_state', 'generate', 'locals', 'dependency', 'dependencies', 'include', 'catalog', 'engine', 'feature', 'exclude', 'errors', 'download_dir', 'prevent_destroy', 'iam_role', 'iam_assume_role_duration', 'iam_assume_role_session_name', 'iam_web_identity_token', 'terraform_binary', 'terraform_version_constraint', 'terragrunt_version_constraint']);
	for (const key of Object.keys(value)) {
		if (!allowed.has(key)) throw new Error(`Unsupported JSON configuration attribute "${key}"`);
	}
}

function usage(): string {
	return [
		'Usage: tghclp hcl validate [options] [directory|file ...]',
		'',
		'Options:',
		'  --json                  Write diagnostics as JSON',
		'  --working-dir <path>   Validate from a working directory',
		'  --show-config-path     List invalid configuration paths',
		'  --experiment <name>   Enable a named experiment',
		'  --help                 Show this help'
	].join('\n');
}

function rootUsage(): string {
	return [
		'Usage: tghclp [global options] <command> [options]',
		'',
		'Main commands:',
		'  run              Run an OpenTofu/Terraform command',
		'  exec             Execute an external command without a shell',
		'  catalog          Browse configured module catalogs',
		'  scaffold         Create a Terragrunt module configuration',
		'',
		'Discovery commands:',
		'  find, fd         Find Terragrunt configurations',
		'  list, ls         List Terragrunt configurations',
		'  dag graph        Graph discovered configurations',
		'',
		'Configuration commands:',
		'  hcl validate     Validate Terragrunt HCL files',
		'  info print       Print evaluation context',
		'',
		'OpenTofu shortcuts:',
		'  apply destroy force-unlock import init output plan refresh show state test validate',
		'    --all, -a         run the dependency graph rather than one unit,',
		'                      as terragrunt\'s `run-all` does',
		'',
		'Global options:',
		'  --allow-path <dir>  let configurations read this directory, which is',
		'                      otherwise refused for being outside the workspace',
		'                      root. Repeatable.',
		'',
		'Use "tghclp <command> --help" for command-specific help.'
	].join('\n');
}

function executionUsage(): string {
	return [
		'Usage: tghclp run [options] -- <tofu/terraform command> [arguments...]',
		'',
		'Options:',
		'  --working-dir <path>   Directory containing Terragrunt configuration',
		'  --tf-path <path>       OpenTofu/Terraform executable (default: tofu)',
		'  --no-color              Disable color output',
		'  --help                  Show this help'
	].join('\n');
}

function discoveryUsage(command: string): string {
	return [
		`Usage: tghclp ${command} [options]`,
		'',
		'Options:',
		'  --working-dir <path>   Directory containing configurations',
		'  --format <format>     text or json (find), text/tree/dot (list)',
		'  --json                Equivalent to --format=json (find)',
		'  --no-hidden           Exclude hidden directories',
		'  --dependencies        Include dependency edges in JSON/DOT output',
		'  --help                Show this help'
	].join('\n');
}

function parseArgs(argv: string[]): CLIOptions | 'help' {
	const options: CLIOptions = { json: false, showConfigPath: false, experiments: [], workingDir: process.cwd(), paths: [], noHidden: false, dependencies: false, dag: false };
	for (let index = 0; index < argv.length; index++) {
		const argument = argv[index];
		if (argument.startsWith('--format=')) {
			const value = argument.slice('--format='.length);
			if (!['text', 'json', 'tree', 'dot'].includes(value)) throw new Error(`Unsupported format ${value}`);
			options.format = value as CLIOptions['format'];
			continue;
		}
		if (argument.startsWith('--working-dir=')) {
			const value = argument.slice('--working-dir='.length);
			if (!value) throw new Error('--working-dir requires a path');
			options.workingDir = path.resolve(value);
			continue;
		}
		// Checked before the switch so the `--terragrunt-` spellings are covered
		// too; a switch can only match the literal names.
		if (isPassthroughFlag(argument)) continue;
		switch (argument) {
			case '--json': options.json = true; options.format = 'json'; break;
			case '--show-config-path': options.showConfigPath = true; break;
			case '--no-hidden': options.noHidden = true; break;
			case '--dependencies': options.dependencies = true; break;
			case '--dag': options.dag = true; break;
			case '--format': {
				const value = argv[++index] as CLIOptions['format'];
				if (!value || !['text', 'json', 'tree', 'dot'].includes(value)) throw new Error(`Unsupported format ${value ?? ''}`);
				options.format = value;
				break;
			}
			case '--no-color':
			case '--no-tips':
			case '--non-interactive':
				break;
			case '--experiment': {
				const value = argv[++index];
				if (!value) throw new Error('--experiment requires a name');
				options.experiments.push(value);
				break;
			}
			case '--working-dir': {
				const value = argv[++index];
				if (!value) throw new Error('--working-dir requires a path');
				options.workingDir = path.resolve(value);
				break;
			}
			case '--help':
			case '-h': return 'help';
			default:
				if (argument.startsWith('-')) throw new Error(`Unknown option ${argument}`);
				options.paths.push(argument);
		}
	}
	return options;
}

interface DiscoveredConfig {
	type: 'unit' | 'stack';
	path: string;
	absPath: string;
}

export async function discoverConfigs(root: string, noHidden: boolean, displayRoot = root): Promise<DiscoveredConfig[]> {
	const result: DiscoveredConfig[] = [];
	const ignored = new Set(['.git', '.scrap', '.terraform', '.terragrunt-cache', '.terragrunt-stack', '.trash', 'node_modules']);
	const walk = async (directory: string): Promise<void> => {
		for (const entry of await fs.readdir(directory, {withFileTypes: true})) {
			if (entry.isDirectory()) {
				if (ignored.has(entry.name) || (noHidden && entry.name.startsWith('.'))) continue;
				await walk(path.join(directory, entry.name));
				continue;
			}
			if (!entry.isFile()) continue;
			if (entry.name !== 'terragrunt.hcl' && entry.name !== 'terragrunt.stack.hcl') continue;
			const absPath = path.join(directory, entry.name);
			result.push({type: entry.name === 'terragrunt.stack.hcl' ? 'stack' : 'unit', path: path.relative(displayRoot, directory) || '.', absPath});
		}
	};
	await walk(root);
	return result.sort((a, b) => a.path.localeCompare(b.path) || a.type.localeCompare(b.type));
}

function printFind(configs: DiscoveredConfig[], options: CLIOptions): void {
	const format = options.format ?? (options.json ? 'json' : 'text');
	if (format === 'json') {
		process.stdout.write(`${JSON.stringify(configs.map(({type, path: configPath}) => ({type, path: configPath})))}\n`);
		return;
	}
	if (format !== 'text') throw new Error(`Unsupported find format ${format}`);
	for (const config of configs) process.stdout.write(`${config.path}\n`);
}

function printList(configs: DiscoveredConfig[], options: CLIOptions): void {
	const format = options.format ?? 'text';
	if (format === 'text') {
		process.stdout.write(`${configs.map(config => config.path).join('  ')}  \n`);
		return;
	}
	if (format === 'tree') {
		for (const config of configs) process.stdout.write(`${config.path}\n`);
		return;
	}
	if (format !== 'dot') throw new Error(`Unsupported list format ${format}`);
	process.stdout.write('digraph {\n');
	for (const config of configs) process.stdout.write(`\t${JSON.stringify(config.path)} ;\n`);
	process.stdout.write('}\n');
}

async function printDependencyGraph(workingDir: string): Promise<void> {
	const workspace = new Workspace();
	workspace.setWorkspaceRoot(pathToFileURL(workingDir).toString());
	const root = await workspace.refreshDependencyTree();
	if (!root) throw new Error(`Unable to construct a configuration graph under ${workingDir}`);
	const nodes: Array<{name: string; parent?: string}> = [];
	const visit = (node: any, parent?: string): void => {
		const fullPath = fileURLToPath(node.data.uri);
		const configDir = node.type === 'workspace'
			? undefined
			: path.basename(fullPath).startsWith('terragrunt.')
				? path.dirname(fullPath)
				: fsSync.existsSync(path.join(fullPath, 'terragrunt.hcl')) ? fullPath : path.dirname(fullPath);
		const name = configDir ? path.resolve(configDir) : undefined;
		if (name) nodes.push({name, parent});
		for (const child of node.children ?? []) visit(child, name);
	};
	visit(root);
	// The tree is walked per path, not per node, so a unit reachable through
	// more than one parent -- every unit that depends on `global`, say -- is
	// pushed once per route and its edges repeat. A directory that resolves to
	// the same config as its parent also produces an edge to itself. Both make
	// the graph unreadable and neither says anything: dedupe, and drop the
	// self-edges.
	const declared = new Set<string>();
	const edges = new Set<string>();
	process.stdout.write('digraph {\n');
	for (const node of nodes) {
		if (declared.has(node.name)) continue;
		declared.add(node.name);
		process.stdout.write(`\t${JSON.stringify(node.name)} ;\n`);
	}
	for (const node of nodes) {
		if (!node.parent || node.parent === node.name) continue;
		const edge = `\t${JSON.stringify(node.parent)} -> ${JSON.stringify(node.name)} ;\n`;
		if (edges.has(edge)) continue;
		edges.add(edge);
		process.stdout.write(edge);
	}
	process.stdout.write('}\n');
}

function printInfo(command: string, workingDir: string): void {
	if (command !== 'print') throw new Error(`Unknown info command ${command}`);
	process.stdout.write(`${JSON.stringify({
		config_path: path.join(workingDir, 'terragrunt.hcl'),
		download_dir: path.join(workingDir, '.terragrunt-cache'),
		iam_role: '',
		terraform_binary: 'tofu',
		terraform_command: 'print',
		working_dir: workingDir
	}, null, 2)}\n`);
}

interface ExecutionOptions {
	workingDir: string;
	tfPath: string;
	args: string[];
	all: boolean;
}

interface FormatOptions {
	workingDir: string;
	tfPath: string;
	check: boolean;
	diff: boolean;
	stdin: boolean;
	files: string[];
}

function parseExecutionArgs(argv: string[]): ExecutionOptions & {command: string} {
	let workingDir = process.cwd();
	let tfPath = process.env.TG_TF_PATH ?? process.env.TERRAGRUNT_TFPATH ?? 'tofu';
	let all = false;
	let index = 0;
	while (index < argv.length) {
		const argument = argv[index];
		if (argument === '--working-dir') {
			const value = argv[++index];
			if (!value) throw new Error('--working-dir requires a path');
			workingDir = path.resolve(value);
			index++;
			continue;
		}
		if (argument.startsWith('--working-dir=')) {
			const value = argument.slice('--working-dir='.length);
			if (!value) throw new Error('--working-dir requires a path');
			workingDir = path.resolve(value);
			index++;
			continue;
		}
		if (argument === '--tf-path') {
			const value = argv[++index];
			if (!value) throw new Error('--tf-path requires a path');
			tfPath = value;
			index++;
			continue;
		}
		if (argument.startsWith('--tf-path=')) {
			tfPath = argument.slice('--tf-path='.length);
			if (!tfPath) throw new Error('--tf-path requires a path');
			index++;
			continue;
		}
		if (isPassthroughFlag(argument)) {
			index++;
			continue;
		}
		if (argument === '--all' || argument === '-a') { all = true; index++; continue; }
		if (argument === '--') {
			index++;
			break;
		}
		break;
	}
	const command = argv[index];
	if (!command || command.startsWith('-')) throw new Error('A Terraform/OpenTofu command is required');
	// Flags belonging to this tool are dropped wherever they appear, not only
	// before the command. Scripts write `run-all apply
	// --terragrunt-non-interactive`, so the flag lands AFTER the command, and
	// forwarding it to OpenTofu makes it reject the whole invocation.
	// Flags that take a VALUE have to consume that value too, or the path is
	// forwarded to OpenTofu as a positional argument. Terragrunt accepts its
	// own flags on either side of the command and consumes them; forwarding
	// them produced "Failed to parse command-line flags" from tofu on an
	// invocation terragrunt accepts.
	const tail = argv.slice(index + 1);
	const args: string[] = [];
	for (let position = 0; position < tail.length; position++) {
		const argument = tail[position];
		if (argument === '--all' || argument === '-a') continue;
		if (isPassthroughFlag(argument)) continue;
		const valued = valuedExecutionFlag(argument);
		if (valued) {
			// `--flag value` consumes the next argument; `--flag=value` is one.
			if (!argument.includes('=')) position++;
			if (valued === 'working-dir') {
				const value = argument.includes('=') ? argument.split('=').slice(1).join('=') : tail[position];
				if (!value) throw new Error('--working-dir requires a path');
				workingDir = path.resolve(value);
			} else if (valued === 'tf-path') {
				const value = argument.includes('=') ? argument.split('=').slice(1).join('=') : tail[position];
				if (!value) throw new Error('--tf-path requires a path');
				tfPath = value;
			}
			continue;
		}
		args.push(argument);
	}
	return {workingDir, tfPath, command, args, all};
}

/**
 * Whether an argument is one of this tool's flags that carries a value.
 *
 * Named rather than pattern-matched, because the answer decides whether the
 * NEXT argument is a value to consume or a flag for OpenTofu, and guessing
 * either way corrupts the invocation. The `--terragrunt-` spellings are
 * accepted alongside the current ones, as everywhere else.
 */
function valuedExecutionFlag(argument: string): 'working-dir' | 'tf-path' | undefined {
	const bare = argument.split('=')[0];
	const name = bare.startsWith('--terragrunt-') ? `--${bare.slice('--terragrunt-'.length)}` : bare;
	if (name === '--working-dir') return 'working-dir';
	if (name === '--tf-path' || name === '--tfpath') return 'tf-path';
	return undefined;
}

function parseFormatArgs(argv: string[]): FormatOptions | 'help' {
	let workingDir = process.cwd();
	let tfPath = process.env.TG_TF_PATH ?? process.env.TERRAGRUNT_TFPATH ?? 'tofu';
	let check = false;
	let diff = false;
	let stdin = false;
	const files: string[] = [];
	for (let index = 0; index < argv.length; index++) {
		const argument = argv[index];
		if (argument === '--help' || argument === '-h') return 'help';
		if (argument === '--check') { check = true; continue; }
		if (argument === '--diff') { diff = true; continue; }
		if (argument === '--stdin') { stdin = true; continue; }
		if (argument === '--working-dir') {
			const value = argv[++index];
			if (!value) throw new Error('--working-dir requires a path');
			workingDir = path.resolve(value);
			continue;
		}
		if (argument.startsWith('--working-dir=')) {
			const value = argument.slice('--working-dir='.length);
			if (!value) throw new Error('--working-dir requires a path');
			workingDir = path.resolve(value);
			continue;
		}
		if (argument === '--tf-path') {
			const value = argv[++index];
			if (!value) throw new Error('--tf-path requires a path');
			tfPath = value;
			continue;
		}
		if (argument.startsWith('--tf-path=')) {
			tfPath = argument.slice('--tf-path='.length);
			if (!tfPath) throw new Error('--tf-path requires a path');
			continue;
		}
		if (isPassthroughFlag(argument)) continue;
		if (argument.startsWith('-')) throw new Error(`Unknown format option ${argument}`);
		files.push(path.resolve(workingDir, argument));
	}
	if (check && diff) throw new Error('--check and --diff cannot be used together');
	if (stdin && files.length > 0) throw new Error('--stdin cannot be combined with file paths');
	return {workingDir, tfPath, check, diff, stdin, files};
}

async function formatHCL(argv: string[]): Promise<number> {
	const options = parseFormatArgs(argv);
	if (options === 'help') {
		console.log('Usage: tghclp hcl format [--check|--diff|--stdin] [--tf-path <path>] [files...]');
		return 0;
	}
	const targets = options.stdin
		? []
		: options.files.length > 0
			? options.files
			: (await collectFiles(options.workingDir)).filter(file => !file.endsWith('.json'));
	if (!options.stdin && targets.length === 0) throw new Error(`No Terragrunt HCL files found under ${options.workingDir}`);
	const tempRoot = await fs.mkdtemp(path.join(options.workingDir, '.tghclp-format-'));
	const changed: string[] = [];
	try {
		if (options.stdin) {
			const original = fsSync.readFileSync(0, 'utf8');
			const tempFile = path.join(tempRoot, 'stdin.tf');
			await fs.writeFile(tempFile, original);
			const result = spawnSync(options.tfPath, ['fmt', tempFile], {encoding: 'utf8', shell: false});
			if (result.error || result.status !== 0) throw new Error(result.error?.message ?? (result.stderr || `Formatter exited with ${result.status}`));
			const formatted = await fs.readFile(tempFile, 'utf8');
			if (options.check && formatted !== original) return 1;
			if (options.diff) {
				if (formatted !== original) process.stdout.write(`--- stdin\n+++ stdin\n${formatted}`);
				return 0;
			}
			process.stdout.write(formatted);
			return 0;
		}
		for (const target of targets) {
			const root = await fs.realpath(options.workingDir);
			const realTarget = await fs.realpath(target);
			const relativeTarget = path.relative(root, realTarget);
			if (relativeTarget === '..' || relativeTarget.startsWith(`..${path.sep}`) || path.isAbsolute(relativeTarget)) {
				throw new Error(`Format target is outside the working directory: ${target}`);
			}
			const info = await fs.stat(target);
			if (!info.isFile()) throw new Error(`Format target is not a file: ${target}`);
			await fs.access(target);
			const original = await fs.readFile(target, 'utf8');
			const tempFile = path.join(tempRoot, `${changed.length}.tf`);
			await fs.writeFile(tempFile, original);
			const result = spawnSync(options.tfPath, ['fmt', tempFile], {encoding: 'utf8', shell: false});
			if (result.error || result.status !== 0) throw new Error(result.error?.message ?? (result.stderr || `Formatter exited with ${result.status}`));
			const formatted = await fs.readFile(tempFile, 'utf8');
			if (formatted === original) continue;
			changed.push(target);
			if (options.check) continue;
			if (options.diff) {
				process.stdout.write(`--- ${target}\n+++ ${target}\n${formatted}`);
				continue;
			}
			await fs.writeFile(target, formatted);
			process.stdout.write(`${target} was updated\n`);
		}
		if (options.check) {
			for (const target of changed) process.stdout.write(`${target} needs formatting\n`);
			return changed.length > 0 ? 1 : 0;
		}
		return 0;
	} finally {
		await fs.rm(tempRoot, {recursive: true, force: true});
	}
}

function offsetPosition(content: string, offset: number): {line: number; character: number} {
	const lines = content.slice(0, offset).split('\n');
	return {line: lines.length - 1, character: lines[lines.length - 1].length};
}

function hclValue(value: unknown): string {
	if (typeof value === 'string') return JSON.stringify(value);
	if (typeof value === 'boolean' || typeof value === 'number') return String(value);
	if (value === null) return 'null';
	if (Array.isArray(value)) return `[${value.map(hclValue).join(', ')}]`;
	if (typeof value === 'object') return `{ ${Object.entries(value as Record<string, unknown>).map(([key, item]) => `${key} = ${hclValue(item)}`).join(', ')} }`;
	throw new Error(`Cannot serialize stack value of type ${typeof value}`);
}

async function copyDirectory(source: string, target: string): Promise<void> {
	await fs.mkdir(target, {recursive: true});
	for (const entry of await fs.readdir(source, {withFileTypes: true})) {
		const from = path.join(source, entry.name);
		const to = path.join(target, entry.name);
		if (entry.isDirectory()) await copyDirectory(from, to);
		else if (entry.isFile()) await fs.copyFile(from, to);
		else throw new Error(`Unsupported stack source entry: ${from}`);
	}
}

export async function stackGenerate(argv: string[]): Promise<number> {
	let workingDir = process.cwd();
	for (let index = 0; index < argv.length; index++) {
		const argument = argv[index];
		if (argument === '--help' || argument === '-h') {
			console.log('Usage: tghclp stack generate [--working-dir <path>]');
			return 0;
		}
		if (argument === '--working-dir') {
			const value = argv[++index];
			if (!value) throw new Error('--working-dir requires a path');
			workingDir = path.resolve(value);
			continue;
		}
		if (argument.startsWith('--working-dir=')) {
			workingDir = path.resolve(argument.slice('--working-dir='.length));
			continue;
		}
		if (isPassthroughFlag(argument)) continue;
		if (argument.startsWith('-')) throw new Error(`Unknown stack generate option ${argument}`);
	}
	const stackPath = path.join(workingDir, 'terragrunt.stack.hcl');
	const content = await fs.readFile(stackPath, 'utf8');
	const document = new ParsedDocument(new Workspace(), pathToFileURL(stackPath).toString(), content);
	const ast: any = document.getAST();
	if (!ast || document.getDiagnostics().length > 0) throw new Error(`Invalid stack configuration: ${stackPath}`);
	const evaluator = evaluatorFor();
	const blocks: any[] = [];
	const visit = (node: any): void => {
		if (node.type === 'block' && (node.value === 'unit' || node.value === 'stack')) blocks.push(node);
		for (const child of node.children ?? []) visit(child);
	};
	visit(ast);
	if (blocks.length === 0) {
		console.warn(`No stack files found in ${workingDir} Nothing to generate.`);
		return 0;
	}
	for (const block of blocks) {
		const attribute = (name: string): any => block.children?.find((child: any) => child.type === 'attribute' && child.value === name);
		const evaluate = async (name: string): Promise<unknown> => {
			const item = attribute(name);
			if (!item) return undefined;
			const value = item.children?.find((child: any) => child.type !== 'attribute_identifier');
			if (!value?.location?.start || value.location.start.offset === undefined) throw new Error(`${name} in ${block.value} is missing a value`);
			const result = await evaluator.evaluateAtPosition(stackPath, content, workingDir, offsetPosition(content, value.location.start.offset));
			if (!result) throw new Error(`Unable to evaluate ${name} in ${stackPath}`);
			return runtimeValueToPlain(result);
		};
		const source = await evaluate('source');
		const generatedPath = await evaluate('path');
		if (typeof source !== 'string' || typeof generatedPath !== 'string' || source === '' || generatedPath === '') throw new Error(`${block.value} requires non-empty source and path attributes`);
		const root = await fs.realpath(workingDir);
		const acquired = await acquireModuleSource(source, root);
		const sourceRelative = path.relative(root, acquired.root);
		if (isLocalSource(splitModuleSource(source).repository) && (sourceRelative === '..' || sourceRelative.startsWith(`..${path.sep}`) || path.isAbsolute(sourceRelative))) {
			await acquired.cleanup();
			throw new Error(`Stack source must be inside the working directory: ${source}`);
		}
		const noDot = Boolean(await evaluate('no_dot_terragrunt_stack'));
		const targetDir = path.resolve(root, noDot ? generatedPath : path.join('.terragrunt-stack', generatedPath));
		try {
			const realSource = acquired.root;
			const relativeTarget = path.relative(root, targetDir);
			if (relativeTarget === '..' || relativeTarget.startsWith(`..${path.sep}`) || path.isAbsolute(relativeTarget)) throw new Error(`Generated stack target is outside the working directory: ${targetDir}`);
			if (realSource === targetDir) throw new Error(`Generated stack source and target are identical: ${targetDir}`);
			await fs.access(realSource);
			await fs.rm(targetDir, {recursive: true, force: true});
			await copyDirectory(realSource, targetDir);
			const values = await evaluate('values');
			if (values !== undefined) {
				if (values === null || typeof values !== 'object' || Array.isArray(values)) throw new Error(`${block.value} values must evaluate to an object`);
				const entries = Object.entries(values as Record<string, unknown>).sort(([left], [right]) => left.localeCompare(right));
				const width = Math.max(...entries.map(([key]) => key.length));
				const valuesText = '# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually\n' + entries.map(([key, value]) => `${key.padEnd(width)} = ${hclValue(value)}`).join('\n') + '\n';
				await fs.writeFile(path.join(targetDir, 'terragrunt.values.hcl'), valuesText);
			}
		} finally {
			await acquired.cleanup();
		}
		console.log(`Generated ${block.value} ${String(block.children?.find((child: any) => child.type === 'parameter')?.value ?? '')}`.trim());
	}
	return 0;
}

async function stackLifecycle(command: 'run' | 'output' | 'clean', argv: string[]): Promise<number> {
	let workingDir = process.cwd();
	for (let index = 0; index < argv.length; index++) {
		if (argv[index] === '--working-dir') {
			const value = argv[++index];
			if (!value) throw new Error('--working-dir requires a path');
			workingDir = path.resolve(value);
		} else if (argv[index]?.startsWith('--working-dir=')) {
			workingDir = path.resolve(argv[index].slice('--working-dir='.length));
		} else if (argv[index] === '--help' || argv[index] === '-h') {
			console.log(`Usage: tghclp stack ${command} [--working-dir <path>]${command === 'run' || command === 'output' ? ' <command> [arguments...]' : ''}`);
			return 0;
		}
	}
	const root = await fs.realpath(workingDir);
	const generated = path.join(root, '.terragrunt-stack');
	if (command === 'clean') {
		await fs.rm(generated, {recursive: true, force: true});
		return 0;
	}
	await stackGenerate(argv.filter((argument, index) => argument === '--working-dir' || argument.startsWith('--working-dir=') || (argv[index - 1] === '--working-dir')));
	const generatedRoot = await fs.realpath(generated);
	const executionArgs = ['--all', '--working-dir', generatedRoot];
	for (let index = 0; index < argv.length; index++) {
		if (argv[index] === '--working-dir') { index++; continue; }
		if (argv[index]?.startsWith('--working-dir=')) continue;
		if (isPassthroughFlag(argv[index])) { executionArgs.push(argv[index]); continue; }
		executionArgs.push(argv[index]);
	}
	if (executionArgs.length === 3) throw new Error(`stack ${command} requires a command`);
	return executeTerraformCommand(executionArgs);
}

async function renderConfig(argv: string[]): Promise<number> {
	let workingDir = process.cwd();
	let configName = 'terragrunt.hcl';
	let json = false;
	for (let index = 0; index < argv.length; index++) {
		const argument = argv[index];
		if (argument === '--help' || argument === '-h') {
			console.log('Usage: tghclp render --json [--working-dir <path>] [--config <file>]');
			return 0;
		}
		if (argument === '--json' || argument === '--format=json') { json = true; continue; }
		if (argument === '--format') {
			const format = argv[++index];
			if (format !== 'json') throw new Error('Only JSON render output is supported');
			json = true;
			continue;
		}
		if (argument === '--working-dir') {
			const value = argv[++index];
			if (!value) throw new Error('--working-dir requires a path');
			workingDir = path.resolve(value);
			continue;
		}
		if (argument === '--config') {
			const value = argv[++index];
			if (!value) throw new Error('--config requires a path');
			configName = value;
			continue;
		}
		if (argument.startsWith('-')) throw new Error(`Unknown render option ${argument}`);
	}
	if (!json) throw new Error('Render output requires --json or --format=json');
	const configPath = path.resolve(workingDir, configName);
	const root = await fs.realpath(workingDir);
	const realConfig = await fs.realpath(configPath);
	const relative = path.relative(root, realConfig);
	if (relative === '..' || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) throw new Error(`Render configuration is outside the working directory: ${configPath}`);
	const content = await fs.readFile(realConfig, 'utf8');
	if (realConfig.endsWith('.json')) {
		const parsed: unknown = JSON.parse(content);
		validateJSONShape(parsed, path.basename(realConfig));
		process.stdout.write(`${JSON.stringify(parsed)}\n`);
		return 0;
	}
	const evaluator = evaluatorFor();
	const result = await evaluator.evaluateRenderedConfig(realConfig, content, root);
	process.stdout.write(`${JSON.stringify(runtimeValueToPlain(result))}\n`);
	return 0;
}

function generatedEntries(value: unknown): Array<[string, Record<string, unknown>]> {
	if (value === null || typeof value !== 'object' || Array.isArray(value)) return [];
	return Object.entries(value as Record<string, unknown>).map(([name, entry]) => {
		if (entry === null || typeof entry !== 'object' || Array.isArray(entry)) throw new Error(`generate "${name}" must evaluate to an object`);
		return [name, entry as Record<string, unknown>];
	});
}

/**
 * The outputs of a unit this one declares a `dependency` on.
 *
 * `dependency.<name>.outputs.<x>` is how one unit reads another, and it is
 * the ordinary way a Terragrunt workspace is wired: the step that provisions
 * reads what the step that planned produced. Without this the reference threw
 * "Dependency has no evaluated outputs" and no configuration using one could
 * be run at all -- the hook existed and nothing supplied it.
 *
 * Resolved the way terragrunt resolves it: find the named block, evaluate its
 * `config_path`, and ask OpenTofu for that unit's outputs. A unit that has
 * not been applied has none, and saying so names the step to run rather than
 * failing on a missing attribute several levels deeper.
 */
/**
 * The OpenTofu or Terraform binary a dependency's outputs are read with.
 *
 * Validation has no `--tf-path` of its own -- it is not running anything --
 * so it follows the same environment variables terragrunt reads, and falls
 * back to the same default.
 */
/**
 * An evaluator configured the way every command needs one.
 *
 * The options were spelled out at eleven call sites. That is how
 * `resolveDependency` came to be supplied at two of them and missing at the
 * rest: a unit reading `dependency.<name>.outputs` evaluated in one command
 * and failed in another, for no reason a reader could see.
 */
function evaluatorFor(options: {
	terraformCommand?: string;
	terraformCliArgs?: string[];
	experiments?: string[];
	tfPath?: string;
} = {}): ConfigEvaluator {
	const tfPath = options.tfPath ?? tfPathForDependencies();
	return new ConfigEvaluator({
		environmentVariables: process.env as Record<string, string>,
		terraformCommand: options.terraformCommand ?? '',
		terraformCliArgs: options.terraformCliArgs ?? [],
		...(options.experiments ? {experiments: options.experiments} : {}),
		workspaceTrusted: true,
		allowedPaths,
		resolveDependency: (from, name) => dependencyOutputs(from, name, tfPath),
	});
}

function tfPathForDependencies(): string {
	return process.env.TG_TF_PATH ?? process.env.TERRAGRUNT_TFPATH ?? 'tofu';
}

async function dependencyOutputs(
	configPath: string,
	name: string,
	tfPath: string
): Promise<RuntimeValue<ValueType> | undefined> {
	const content = await fs.readFile(configPath, 'utf8');
	const ast: any = parse(content, {grammarSource: configPath, tracer: {trace() {}}});
	let target: string | undefined;
	const visit = async (node: any): Promise<void> => {
		if (target) return;
		if (node.type === 'block' && node.value === 'dependency') {
			const label = node.children?.find((child: any) => child.type === 'parameter');
			if (label && String(label.value) === name) {
				const attribute = node.children?.find(
					(child: any) => child.type === 'attribute' && child.value === 'config_path'
				);
				const valueNode = attribute?.children?.find((child: any) => child.type !== 'attribute_identifier');
				if (!valueNode) throw new Error(`dependency "${name}" in ${configPath} is missing config_path`);
				// Read as a literal, not evaluated. Evaluating an expression in
				// this file re-enters evaluation of the whole unit -- including
				// the `dependency.<name>.outputs` reference that called this --
				// and the recursion surfaces as the very error it is resolving.
				//
				// `config_path` is a path to a sibling unit. An interpolated one
				// is refused rather than guessed at, because a path this cannot
				// read is a dependency it would silently fail to find.
				const literal = String(valueNode.value ?? '');
				if (!literal) {
					throw new Error(
						`dependency "${name}" in ${configPath} has a config_path this cannot read ` +
						'without evaluating the unit it belongs to. Write it as a literal path.'
					);
				}
				target = path.resolve(path.dirname(configPath), literal);
			}
		}
		for (const child of node.children ?? []) await visit(child);
	};
	await visit(ast);
	if (!target) return undefined;

	const result = spawnSync(tfPath, ['output', '-json'], {cwd: target, encoding: 'utf8'});
	if (result.status !== 0) {
		throw new Error(
			`dependency "${name}" has no outputs to read from ${target}.\n` +
			`Apply that unit first. ${(result.stderr || '').trim().split('\n')[0]}`
		);
	}
	// `output -json` gives {name: {value, type, sensitive}}; a dependency reads
	// the values.
	const raw = JSON.parse(result.stdout || '{}') as Record<string, {value: unknown}>;
	const outputs = new Map<string, RuntimeValue<ValueType>>();
	for (const [key, entry] of Object.entries(raw)) {
		outputs.set(key, convertToRuntimeValue(entry.value));
	}
	return makeObjectValue(new Map([['outputs', makeObjectValue(outputs)]]));
}

async function materializeGeneratedFiles(
	configPath: string,
	content: string,
	workDir: string,
	tfPath: string
): Promise<void> {
	// A generate block may interpolate a dependency's outputs, so rendering one
	// needs the same resolution running a unit does.
	const evaluator = evaluatorFor({tfPath});
	const rendered = runtimeValueToPlain(await evaluator.evaluateRenderedConfig(configPath, content, workDir)) as Record<string, unknown>;
	const generate = generatedEntries(rendered.generate);
	for (const [name, entry] of generate) {
		const relativePath = entry.path;
		const contents = entry.contents;
		if (typeof relativePath !== 'string' || relativePath.length === 0) throw new Error(`generate "${name}" requires a non-empty path`);
		if (typeof contents !== 'string') throw new Error(`generate "${name}" requires string contents`);
		const root = await fs.realpath(workDir);
		const target = path.resolve(path.dirname(configPath), relativePath);
		// Both sides through realpath, or the comparison is between two
		// spellings of the same place. On macOS /var is a symlink to
		// /private/var, so a working directory under $TMPDIR resolved on one
		// side and not the other, and every generated file looked like an
		// escape from a directory it was sitting inside.
		//
		// The target may not exist yet -- it is what is about to be written --
		// so its DIRECTORY is resolved and the name appended.
		const targetDirectory = await fs.realpath(path.dirname(target));
		const resolvedTarget = path.join(targetDirectory, path.basename(target));
		const relative = path.relative(root, resolvedTarget);
		if (relative === '..' || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) throw new Error(`Generated file is outside the working directory: ${target}`);
		const exists = await pathExists(target);
		const ifExists = typeof entry.if_exists === 'string' ? entry.if_exists : 'overwrite_terragrunt';
		if (exists && (ifExists === 'skip' || ifExists === 'skip_if_exists')) continue;
		if (exists && ifExists === 'error') throw new Error(`Generated file already exists: ${target}`);
		// `overwrite_terragrunt` means "overwrite a file THIS TOOL generated",
		// not "overwrite whatever is there". Terragrunt enforces that with a
		// signature line and refuses a file without one, which is what stops a
		// generate block silently destroying something hand-written that
		// happens to share the name.
		if (exists && ifExists === 'overwrite_terragrunt') {
			const existing = await fs.readFile(target, 'utf8');
			if (!existing.startsWith(GENERATED_SIGNATURE)) {
				throw new Error(
					`Refusing to overwrite ${target}: it exists and was not generated by tghclparser`
				);
			}
		}
		await fs.mkdir(path.dirname(target), {recursive: true});
		await fs.writeFile(target, `${GENERATED_SIGNATURE}\n${contents}`, 'utf8');
	}
}

interface ScaffoldVariable {
	name: string;
	description?: string;
	defaultValue?: unknown;
}

interface AcquiredSource {
	root: string;
	source: string;
	cleanup: () => Promise<void>;
}

function splitModuleSource(source: string): {repository: string; subdirectory: string; ref?: string; forced?: string} {
	let value = source.trim();
	let forced: string | undefined;
	const forcedMatch = value.match(/^([a-z][a-z0-9+.-]*):\:/i);
	if (forcedMatch) {
		forced = forcedMatch[1].toLowerCase();
		value = value.slice(forcedMatch[0].length);
	}
	const queryIndex = value.indexOf('?');
	const query = queryIndex >= 0 ? new URLSearchParams(value.slice(queryIndex + 1)) : new URLSearchParams();
	if (queryIndex >= 0) value = value.slice(0, queryIndex);
	let repository = value;
	let subdirectory = '';
	const protocolEnd = value.indexOf('://');
	const searchStart = protocolEnd >= 0 ? protocolEnd + 3 : 0;
	const separator = value.indexOf('//', searchStart);
	if (separator >= 0) {
		repository = value.slice(0, separator);
		subdirectory = value.slice(separator + 2);
	}
	return {repository, subdirectory, ref: query.get('ref') || undefined, forced};
}

function providerCommand(name: string, args: string[], workingDir: string): void {
	const result = spawnSync(name, args, {cwd: workingDir, encoding: 'utf8', shell: false, stdio: ['ignore', 'pipe', 'pipe']});
	if (result.error) throw new Error(`Unable to execute provider command ${name}: ${result.error.message}`);
	if (result.status !== 0) throw new Error(`${name} ${args.join(' ')} failed: ${(result.stderr || result.stdout || `exit status ${result.status}`).trim()}`);
}

function backendConfigObject(remoteState: Record<string, unknown>): Record<string, unknown> {
	const config = remoteState.config;
	if (config === null || typeof config !== 'object' || Array.isArray(config)) throw new Error('remote_state.config must be an object');
	return config as Record<string, unknown>;
}

function requiredConfigString(config: Record<string, unknown>, key: string): string {
	const value = config[key];
	if (typeof value !== 'string' || value.length === 0) throw new Error(`remote_state.config.${key} must be a non-empty string`);
	return value;
}

function backendBootstrap(backend: string, config: Record<string, unknown>, workingDir: string): void {
	if (backend === 's3') {
		const bucket = requiredConfigString(config, 'bucket');
		const region = typeof config.region === 'string' && config.region.length > 0 ? config.region : undefined;
		const head = spawnSync('aws', ['s3api', 'head-bucket', '--bucket', bucket], {cwd: workingDir, encoding: 'utf8', shell: false, stdio: ['ignore', 'pipe', 'pipe']});
		if (head.error) throw new Error(`Unable to execute provider command aws: ${head.error.message}`);
		if (head.status !== 0) {
			const create = ['s3api', 'create-bucket', '--bucket', bucket];
			if (region && region !== 'us-east-1') create.push('--create-bucket-configuration', `LocationConstraint=${region}`);
			providerCommand('aws', create, workingDir);
		}
		providerCommand('aws', ['s3api', 'put-bucket-versioning', '--bucket', bucket, '--versioning-configuration', 'Status=Enabled'], workingDir);
		const table = typeof config.dynamodb_table === 'string' ? config.dynamodb_table : '';
		if (table) {
			const describe = spawnSync('aws', ['dynamodb', 'describe-table', '--table-name', table], {cwd: workingDir, encoding: 'utf8', shell: false, stdio: ['ignore', 'pipe', 'pipe']});
			if (describe.error) throw new Error(`Unable to execute provider command aws: ${describe.error.message}`);
			if (describe.status !== 0) providerCommand('aws', ['dynamodb', 'create-table', '--table-name', table, '--attribute-definitions', 'AttributeName=LockID,AttributeType=S', '--key-schema', 'AttributeName=LockID,KeyType=HASH', '--billing-mode', 'PAY_PER_REQUEST'], workingDir);
		}
		return;
	}
	if (backend === 'gcs') {
		const bucket = requiredConfigString(config, 'bucket');
		const describe = spawnSync('gcloud', ['storage', 'buckets', 'describe', `gs://${bucket}`], {cwd: workingDir, encoding: 'utf8', shell: false, stdio: ['ignore', 'pipe', 'pipe']});
		if (describe.error) throw new Error(`Unable to execute provider command gcloud: ${describe.error.message}`);
		if (describe.status !== 0) {
			const create = ['storage', 'buckets', 'create', `gs://${bucket}`];
			if (typeof config.location === 'string' && config.location) create.push('--location', config.location);
			providerCommand('gcloud', create, workingDir);
		}
		providerCommand('gcloud', ['storage', 'buckets', 'update', `gs://${bucket}`, '--versioning'], workingDir);
		return;
	}
	if (backend === 'azurerm') {
		const account = requiredConfigString(config, 'storage_account_name');
		const container = requiredConfigString(config, 'container_name');
		const show = spawnSync('az', ['storage', 'container', 'show', '--account-name', account, '--name', container, '--auth-mode', 'login'], {cwd: workingDir, encoding: 'utf8', shell: false, stdio: ['ignore', 'pipe', 'pipe']});
		if (show.error) throw new Error(`Unable to execute provider command az: ${show.error.message}`);
		if (show.status !== 0) providerCommand('az', ['storage', 'container', 'create', '--account-name', account, '--name', container, '--auth-mode', 'login'], workingDir);
		return;
	}
	throw new Error(`Unsupported remote state backend: ${backend}`);
}

function backendMigrate(backend: string, source: Record<string, unknown>, destination: Record<string, unknown>, workingDir: string): void {
	if (backend === 's3') {
		const sourceBucket = requiredConfigString(source, 'bucket');
		const sourceKey = requiredConfigString(source, 'key');
		const destinationBucket = requiredConfigString(destination, 'bucket');
		const destinationKey = requiredConfigString(destination, 'key');
		providerCommand('aws', ['s3api', 'copy-object', '--copy-source', `${sourceBucket}/${sourceKey}`, '--bucket', destinationBucket, '--key', destinationKey], workingDir);
		providerCommand('aws', ['s3api', 'delete-object', '--bucket', sourceBucket, '--key', sourceKey], workingDir);
		return;
	}
	if (backend === 'gcs') {
		const sourceBucket = requiredConfigString(source, 'bucket');
		const destinationBucket = requiredConfigString(destination, 'bucket');
		const sourcePrefix = typeof source.prefix === 'string' ? source.prefix : 'default.tfstate';
		const destinationPrefix = typeof destination.prefix === 'string' ? destination.prefix : 'default.tfstate';
		providerCommand('gcloud', ['storage', 'cp', `gs://${sourceBucket}/${sourcePrefix || 'default.tfstate'}`, `gs://${destinationBucket}/${destinationPrefix || 'default.tfstate'}`], workingDir);
		providerCommand('gcloud', ['storage', 'rm', `gs://${sourceBucket}/${sourcePrefix || 'default.tfstate'}`], workingDir);
		return;
	}
	if (backend === 'azurerm') {
		const sourceAccount = requiredConfigString(source, 'storage_account_name');
		const sourceContainer = requiredConfigString(source, 'container_name');
		const sourceKey = requiredConfigString(source, 'key');
		const destinationAccount = requiredConfigString(destination, 'storage_account_name');
		const destinationContainer = requiredConfigString(destination, 'container_name');
		const destinationKey = requiredConfigString(destination, 'key');
		if (sourceAccount !== destinationAccount) throw new Error('azurerm backend migration across storage accounts requires separate pull and push credentials');
		providerCommand('az', ['storage', 'blob', 'copy', 'start', '--account-name', sourceAccount, '--destination-account-name', destinationAccount, '--source-container', sourceContainer, '--source-blob', sourceKey, '--destination-container', destinationContainer, '--destination-blob', destinationKey, '--auth-mode', 'login'], workingDir);
		providerCommand('az', ['storage', 'blob', 'delete', '--account-name', sourceAccount, '--container-name', sourceContainer, '--name', sourceKey, '--auth-mode', 'login'], workingDir);
		return;
	}
	throw new Error(`Unsupported remote state backend: ${backend}`);
}

function backendDelete(backend: string, config: Record<string, unknown>, workingDir: string): void {
	if (backend === 's3') {
		const bucket = requiredConfigString(config, 'bucket');
		const key = requiredConfigString(config, 'key');
		const table = typeof config.dynamodb_table === 'string' ? config.dynamodb_table : '';
		if (table) {
			const lockKey = `${bucket}/${key}-md5`;
			providerCommand('aws', ['dynamodb', 'delete-item', '--table-name', table, '--key', `LockID={S=${lockKey}}`], workingDir);
		}
		providerCommand('aws', ['s3api', 'delete-object', '--bucket', bucket, '--key', key], workingDir);
		return;
	}
	if (backend === 'gcs') {
		const bucket = requiredConfigString(config, 'bucket');
		const prefix = requiredConfigString(config, 'prefix');
		providerCommand('gcloud', ['storage', 'rm', `gs://${bucket}/${prefix}`], workingDir);
		return;
	}
	if (backend === 'azurerm') {
		const account = requiredConfigString(config, 'storage_account_name');
		const container = requiredConfigString(config, 'container_name');
		const key = requiredConfigString(config, 'key');
		providerCommand('az', ['storage', 'blob', 'delete', '--account-name', account, '--container-name', container, '--name', key, '--auth-mode', 'login'], workingDir);
		return;
	}
	throw new Error(`Unsupported remote state backend: ${backend}`);
}

function isLocalSource(source: string): boolean {
	return source.startsWith('./') || source.startsWith('../') || source.startsWith('/') || source.startsWith('file://');
}

function isArchiveSource(source: string): boolean {
	return /\.(zip|tar|tgz|tar\.gz)(?:\?.*)?$/i.test(source);
}

async function verifyExtractedTree(root: string): Promise<void> {
	const canonicalRoot = await fs.realpath(root);
	const walk = async (directory: string): Promise<void> => {
		for (const entry of await fs.readdir(directory, {withFileTypes: true})) {
			const target = path.join(directory, entry.name);
			const canonical = await fs.realpath(target);
			const relative = path.relative(canonicalRoot, canonical);
			if (relative === '..' || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) throw new Error(`Acquired source contains an entry outside its extraction root: ${entry.name}`);
			if (entry.isDirectory()) await walk(target);
		}
	};
	await walk(root);
}

async function acquireArchiveSource(source: string, workingDir: string, subdirectory: string): Promise<AcquiredSource> {
	const temporary = await fs.mkdtemp(path.join(await fs.realpath(workingDir), '.tghclp-source-'));
	const archive = path.join(temporary, path.basename(new URL(source).pathname) || 'source.archive');
	const downloaded = spawnSync('curl', ['--fail', '--location', '--silent', '--show-error', '--output', archive, source], {cwd: workingDir, encoding: 'utf8', shell: false, stdio: ['ignore', 'pipe', 'pipe']});
	if (downloaded.error || downloaded.status !== 0) {
		await fs.rm(temporary, {recursive: true, force: true});
		throw new Error(`Unable to download module archive ${source}: ${(downloaded.stderr || downloaded.error?.message || 'curl failed').trim()}`);
	}
	const extraction = path.join(temporary, 'extracted');
	await fs.mkdir(extraction);
	const archiveName = archive.toLowerCase();
	const extractor = archiveName.endsWith('.zip') ? spawnSync('unzip', ['-q', archive, '-d', extraction], {cwd: workingDir, encoding: 'utf8', shell: false, stdio: ['ignore', 'pipe', 'pipe']}) : spawnSync('tar', ['-xf', archive, '-C', extraction], {cwd: workingDir, encoding: 'utf8', shell: false, stdio: ['ignore', 'pipe', 'pipe']});
	if (extractor.error || extractor.status !== 0) {
		await fs.rm(temporary, {recursive: true, force: true});
		throw new Error(`Unable to extract module archive ${source}: ${(extractor.stderr || extractor.error?.message || 'archive extraction failed').trim()}`);
	}
	await verifyExtractedTree(extraction);
	const entries = await fs.readdir(extraction, {withFileTypes: true});
	const base = entries.length === 1 && entries[0].isDirectory() ? path.join(extraction, entries[0].name) : extraction;
	let selected: string;
	if (!subdirectory) selected = await fs.realpath(base);
	else {
		const direct = path.resolve(extraction, subdirectory);
		const nested = path.resolve(base, subdirectory);
		selected = await fs.realpath(await pathExists(direct) ? direct : nested);
	}
	const relative = path.relative(extraction, selected);
	if (relative === '..' || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) {
		await fs.rm(temporary, {recursive: true, force: true});
		throw new Error(`Module archive subdirectory escapes extraction root: ${source}`);
	}
	return {root: selected, source, cleanup: async () => { await fs.rm(temporary, {recursive: true, force: true}); }};
}

async function acquireModuleSource(source: string, workingDir: string): Promise<AcquiredSource> {
	const parts = splitModuleSource(source);
	if (parts.forced === 'hg') {
		const temporary = await fs.mkdtemp(path.join(await fs.realpath(workingDir), '.tghclp-source-'));
		const cloneTarget = path.join(temporary, 'repository');
		const args = ['clone'];
		if (parts.ref) args.push('--updaterev', parts.ref);
		args.push(parts.repository, cloneTarget);
		const result = spawnSync('hg', args, {cwd: workingDir, encoding: 'utf8', shell: false, stdio: ['ignore', 'pipe', 'pipe']});
		if (result.error || result.status !== 0) {
			await fs.rm(temporary, {recursive: true, force: true});
			throw new Error(`Unable to acquire Mercurial module source ${source}: ${(result.stderr || result.error?.message || 'hg clone failed').trim()}`);
		}
		const selected = parts.subdirectory ? await fs.realpath(path.resolve(cloneTarget, parts.subdirectory)) : await fs.realpath(cloneTarget);
		const relative = path.relative(cloneTarget, selected);
		if (relative === '..' || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) {
			await fs.rm(temporary, {recursive: true, force: true});
			throw new Error(`Mercurial source subdirectory escapes repository: ${source}`);
		}
		return {root: selected, source, cleanup: async () => { await fs.rm(temporary, {recursive: true, force: true}); }};
	}
	if (isLocalSource(parts.repository)) {
		const local = parts.repository.startsWith('file://')
			? fileURLToPath(new URL(parts.repository))
			: path.resolve(workingDir, parts.repository);
		const root = await fs.realpath(local);
		const selected = parts.subdirectory ? await fs.realpath(path.resolve(root, parts.subdirectory)) : root;
		const relative = path.relative(root, selected);
		if (relative === '..' || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) throw new Error(`Module source subdirectory escapes repository: ${source}`);
		await fs.access(selected);
		return {root: selected, source, cleanup: async () => {}};
	}
	if (/^https?:/i.test(parts.repository) && isArchiveSource(parts.repository)) return acquireArchiveSource(parts.repository, workingDir, parts.subdirectory);
	if (!/^(https?|ssh):|^git@/i.test(parts.repository)) throw new Error(`Unsupported module source: ${source}`);
	const temporary = await fs.mkdtemp(path.join(await fs.realpath(workingDir), '.tghclp-source-'));
	const cloneTarget = path.join(temporary, 'repository');
	const args = ['clone', '--depth', '1'];
	if (parts.ref) args.push('--branch', parts.ref);
	args.push(parts.repository, cloneTarget);
	const result = spawnSync('git', args, {cwd: workingDir, encoding: 'utf8', shell: false, stdio: ['ignore', 'pipe', 'pipe']});
	if (result.error || result.status !== 0) {
		await fs.rm(temporary, {recursive: true, force: true});
		throw new Error(`Unable to acquire module source ${source}: ${(result.stderr || result.error?.message || 'git clone failed').trim()}`);
	}
	const selected = parts.subdirectory ? await fs.realpath(path.resolve(cloneTarget, parts.subdirectory)) : await fs.realpath(cloneTarget);
	const relative = path.relative(cloneTarget, selected);
	if (relative === '..' || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) {
		await fs.rm(temporary, {recursive: true, force: true});
		throw new Error(`Module source subdirectory escapes repository: ${source}`);
	}
	return {root: selected, source, cleanup: async () => { await fs.rm(temporary, {recursive: true, force: true}); }};
}

async function scaffoldLocal(argv: string[]): Promise<number> {
	let workingDir = process.cwd();
	let outputFolder = process.cwd();
	let rootFileName = 'root.hcl';
	let includeRoot = true;
	const variables = new Map<string, unknown>();
	let moduleURL = '';
	for (let index = 0; index < argv.length; index++) {
		const argument = argv[index];
		if (argument === '--help' || argument === '-h') {
			console.log('Usage: tghclp scaffold <local-module> [--output-folder <path>] [--var name=value] [--no-include-root]');
			return 0;
		}
		if (argument === '--working-dir' || argument === '--output-folder' || argument === '--root-file-name' || argument === '--var') {
			const value = argv[++index];
			if (!value) throw new Error(`${argument} requires a value`);
			if (argument === '--working-dir') workingDir = path.resolve(value);
			else if (argument === '--output-folder') outputFolder = path.resolve(workingDir, value);
			else if (argument === '--root-file-name') rootFileName = value;
			else {
				const split = value.indexOf('=');
				if (split <= 0) throw new Error('--var must use name=value');
				variables.set(value.slice(0, split), value.slice(split + 1));
			}
			continue;
		}
		if (argument === '--no-include-root') { includeRoot = false; continue; }
		if (isPassthroughFlag(argument)) continue;
		if (argument.startsWith('-')) throw new Error(`Unknown scaffold option ${argument}`);
		if (moduleURL) throw new Error('Only one module source may be scaffolded');
		moduleURL = argument;
	}
	if (!moduleURL) throw new Error('A module source is required');
	const root = await fs.realpath(workingDir);
	const acquired = await acquireModuleSource(moduleURL, root);
	const moduleDir = acquired.root;
	const relativeModule = path.relative(root, moduleDir);
	if (isLocalSource(splitModuleSource(moduleURL).repository) && (relativeModule === '..' || relativeModule.startsWith(`..${path.sep}`) || path.isAbsolute(relativeModule))) {
		await acquired.cleanup();
		throw new Error('Scaffold source must be inside the working directory');
	}
	outputFolder = path.join(await fs.realpath(path.dirname(outputFolder)), path.basename(outputFolder));
	const relativeOutput = path.relative(root, outputFolder);
	if (relativeOutput === '..' || relativeOutput.startsWith(`..${path.sep}`) || path.isAbsolute(relativeOutput)) throw new Error('Scaffold output must be inside the working directory');
	try {
	const files: string[] = [];
	const walk = async (directory: string): Promise<void> => {
		for (const entry of await fs.readdir(directory, {withFileTypes: true})) {
			const target = path.join(directory, entry.name);
			if (entry.isDirectory()) await walk(target);
			else if (entry.isFile() && entry.name.endsWith('.tf')) files.push(target);
		}
	};
	await walk(moduleDir);
	const evaluator = evaluatorFor();
	const discovered: ScaffoldVariable[] = [];
	for (const file of files.sort()) {
		const content = await fs.readFile(file, 'utf8');
		const ast: any = parse(content, {grammarSource: file, tracer: {trace() {}}});
		for (const block of ast.children ?? []) {
			if (block.type !== 'block' || block.value !== 'variable') continue;
			const label = block.children?.find((child: any) => child.type === 'parameter');
			if (!label) throw new Error(`Variable block in ${file} has no name`);
			const item: ScaffoldVariable = {name: String(label.value)};
			for (const child of block.children ?? []) {
				if (child.type !== 'attribute') continue;
				const valueNode = child.children?.find((value: any) => value.type !== 'attribute_identifier');
				if (!valueNode) continue;
				if (child.value === 'description') {
					const value = await evaluator.evaluateAtPosition(file, content, moduleDir, offsetPosition(content, valueNode.location.start.offset));
					if (value?.type === 'string') item.description = String(value.value);
				}
				if (child.value === 'default') {
					const value = await evaluator.evaluateAtPosition(file, content, moduleDir, offsetPosition(content, valueNode.location.start.offset));
					if (value) item.defaultValue = runtimeValueToPlain(value);
				}
			}
			discovered.push(item);
		}
	}
	const inputs = new Map<string, unknown>();
	for (const variable of discovered) {
		if (variables.has(variable.name)) inputs.set(variable.name, variables.get(variable.name));
		else if (variable.defaultValue !== undefined) inputs.set(variable.name, variable.defaultValue);
		else throw new Error(`Required module variable "${variable.name}" needs --var ${variable.name}=...`);
	}
	await fs.mkdir(outputFolder, {recursive: true});
	const configLines = [`terraform {`, `  source = ${JSON.stringify(moduleURL)}`, `}`, ''];
	if (includeRoot) configLines.push('include "root" {', `  path = find_in_parent_folders(${JSON.stringify(rootFileName)})`, '}', '');
	configLines.push('inputs = {');
	for (const [name, value] of [...inputs.entries()].sort(([left], [right]) => left.localeCompare(right))) configLines.push(`  ${name} = ${hclValue(value)}`);
	configLines.push('}', '');
	const target = path.join(outputFolder, 'terragrunt.hcl');
	if (await pathExists(target)) throw new Error(`Scaffold target already exists: ${target}`);
	await fs.writeFile(target, configLines.join('\n'), 'utf8');
	console.log(`Scaffolded ${target}`);
	return 0;
	} finally {
		await acquired.cleanup();
	}
}

async function catalogJSONL(argv: string[]): Promise<number> {
	let workingDir = process.cwd();
	let format = 'tui';
	let experiment = false;
	for (let index = 0; index < argv.length; index++) {
		const argument = argv[index];
		if (argument === '--help' || argument === '-h') {
			console.log('Usage: tghclp catalog --format=jsonl --experiment=catalog-format [--working-dir <path>]');
			return 0;
		}
		if (argument === '--experiment=catalog-format' || (argument === '--experiment' && argv[++index] === 'catalog-format')) { experiment = true; continue; }
		if (argument === '--format') { format = argv[++index] ?? ''; continue; }
		if (argument.startsWith('--format=')) { format = argument.slice('--format='.length); continue; }
		if (argument === '--working-dir') { workingDir = path.resolve(argv[++index] ?? ''); continue; }
		if (argument.startsWith('--working-dir=')) { workingDir = path.resolve(argument.slice('--working-dir='.length)); continue; }
		if (isPassthroughFlag(argument)) continue;
		if (argument.startsWith('-')) throw new Error(`Unknown catalog option ${argument}`);
	}
	if (format !== 'jsonl') throw new Error('Interactive catalog browsing is not available; use --format=jsonl');
	if (!experiment) throw new Error("non-interactive catalog formats require usage of the 'catalog-format' experiment");
	const configPath = path.join(workingDir, 'terragrunt.hcl');
	const content = await fs.readFile(configPath, 'utf8');
	const evaluator = evaluatorFor();
	const rendered = runtimeValueToPlain(await evaluator.evaluateRenderedConfig(configPath, content, workingDir)) as Record<string, unknown>;
	const catalog = rendered.catalog;
	if (catalog === null || typeof catalog !== 'object' || Array.isArray(catalog)) throw new Error('catalog configuration is required');
	const urls = (catalog as Record<string, unknown>).urls;
	if (!Array.isArray(urls) || urls.some(url => typeof url !== 'string')) throw new Error('catalog.urls must be a list of strings');
	for (const source of urls as string[]) {
		const acquired = await acquireModuleSource(source, workingDir);
		try {
			const catalogRoot = acquired.root;
			const components = await discoverConfigs(catalogRoot, false, catalogRoot);
			for (const component of components.filter(item => item.type === 'unit')) {
			const componentContent = await fs.readFile(component.absPath, 'utf8');
			const componentRendered = runtimeValueToPlain(await evaluator.evaluateRenderedConfig(component.absPath, componentContent, workingDir)) as Record<string, unknown>;
			const terraform = componentRendered.terraform as Record<string, unknown> | undefined;
			process.stdout.write(`${JSON.stringify({kind: 'unit', title: path.basename(component.path), description: '', source, dir: component.path, component_source: terraform?.source ?? '', copyable: true})}\n`);
			}
		} finally {
			await acquired.cleanup();
		}
	}
	return 0;
}

async function backendCommand(argv: string[]): Promise<number> {
	const operation = argv[0];
	if (!operation || operation === '--help' || operation === '-h') {
		console.log('Usage: tghclp backend <bootstrap|delete|migrate> [options]');
		return 0;
	}
	if (!['bootstrap', 'delete', 'migrate'].includes(operation)) throw new Error(`Unknown backend operation ${operation}`);
	let workingDir = process.cwd();
	let tfPath = process.env.TG_TF_PATH ?? process.env.TERRAGRUNT_TFPATH ?? 'tofu';
	let force = false;
	const positional: string[] = [];
	for (let index = 1; index < argv.length; index++) {
		const argument = argv[index];
		if (argument === '--help' || argument === '-h') {
			console.log(`Usage: tghclp backend ${operation} [--working-dir <path>] [--tf-path <path>]${operation === 'migrate' ? ' <src-unit> <dst-unit>' : ''}`);
			return 0;
		}
		if (argument === '--working-dir') { workingDir = path.resolve(argv[++index] ?? ''); continue; }
		if (argument.startsWith('--working-dir=')) { workingDir = path.resolve(argument.slice('--working-dir='.length)); continue; }
		if (argument === '--tf-path') { tfPath = argv[++index] ?? ''; if (!tfPath) throw new Error('--tf-path requires a path'); continue; }
		if (argument.startsWith('--tf-path=')) { tfPath = argument.slice('--tf-path='.length); continue; }
		if (argument === '--force') { force = true; continue; }
		if (isPassthroughFlag(argument)) continue;
		if (argument.startsWith('-')) throw new Error(`Unknown backend option ${argument}`);
		positional.push(argument);
	}
	if (operation === 'migrate') {
		if (positional.length !== 2) throw new Error('backend migrate requires <src-unit> and <dst-unit>');
		const sourceDir = path.resolve(workingDir, positional[0]);
		const destination = path.resolve(workingDir, positional[1]);
		const sourcePath = path.join(sourceDir, 'terragrunt.hcl');
		const destinationPath = path.join(destination, 'terragrunt.hcl');
		const sourceContent = await fs.readFile(sourcePath, 'utf8');
		const destinationContent = await fs.readFile(destinationPath, 'utf8');
		const evaluator = evaluatorFor();
		const sourceRendered = runtimeValueToPlain(await evaluator.evaluateRenderedConfig(sourcePath, sourceContent, workingDir)) as Record<string, unknown>;
		const destinationRendered = runtimeValueToPlain(await evaluator.evaluateRenderedConfig(destinationPath, destinationContent, workingDir)) as Record<string, unknown>;
		const sourceState = sourceRendered.remote_state as Record<string, unknown> | undefined;
		const destinationState = destinationRendered.remote_state as Record<string, unknown> | undefined;
		if (!sourceState || !destinationState || typeof sourceState.backend !== 'string' || sourceState.backend !== destinationState.backend) throw new Error('backend migrate requires matching source and destination remote_state backends');
		backendMigrate(sourceState.backend, backendConfigObject(sourceState), backendConfigObject(destinationState), workingDir);
		return 0;
	}
	const configPath = path.join(workingDir, 'terragrunt.hcl');
	const content = await fs.readFile(configPath, 'utf8');
	const evaluator = evaluatorFor();
	const rendered = runtimeValueToPlain(await evaluator.evaluateRenderedConfig(configPath, content, workingDir)) as Record<string, unknown>;
	const remoteState = rendered.remote_state as Record<string, unknown> | undefined;
	if (!remoteState || typeof remoteState.backend !== 'string') throw new Error('remote_state.backend is required for backend operations');
	if (operation === 'bootstrap') {
		if (remoteState.backend === 'local') {
			console.warn('Bootstrap for local backend not implemented.');
			return 0;
		}
		backendBootstrap(remoteState.backend, backendConfigObject(remoteState), workingDir);
		return 0;
	}
	if (!force) throw new Error('backend delete requires --force');
	if (remoteState.backend === 'local') {
		console.warn('Delete for local backend not implemented.');
		return 0;
	}
	backendDelete(remoteState.backend, backendConfigObject(remoteState), workingDir);
	return 0;
}

async function executeTerraformCommand(argv: string[]): Promise<number> {
	const options = parseExecutionArgs(argv);
	const stackPath = path.join(options.workingDir, 'terragrunt.stack.hcl');
	const executionWorkingDir = await pathExists(stackPath) ? path.join(options.workingDir, '.terragrunt-stack') : options.workingDir;
	if (await pathExists(stackPath)) await stackGenerate(['--working-dir', options.workingDir]);
	const configFiles = (await collectFiles(executionWorkingDir)).filter(file => path.basename(file) === 'terragrunt.hcl' || path.basename(file) === 'terragrunt.hcl.json');
	if (configFiles.length === 0) throw new Error(`No Terragrunt HCL files found under ${executionWorkingDir}`);
	const diagnostics = (await Promise.all(configFiles.map(file => validateFile(file, executionWorkingDir, [])))).flat();
	if (diagnostics.length > 0) {
		for (const item of diagnostics) process.stderr.write(`${item.range.filename}: ${item.summary}: ${item.detail}\n`);
		return 1;
	}
	const discovered = await dependencyOrderedFiles(configFiles);
	let selected: string[];
	if (options.all) selected = discovered;
	else {
		const rootConfig = configFiles.find(file => path.dirname(file) === executionWorkingDir);
		if (rootConfig) selected = [rootConfig];
		else if (configFiles.length === 1) selected = [configFiles[0]];
		else throw new Error(`Multiple units found under ${options.workingDir}; use --all to run the dependency graph`);
	}
	const executable = options.tfPath;
	for (const configFile of selected) {
		const unitDir = path.dirname(configFile);
		const content = await fs.readFile(configFile, 'utf8');
		let rendered: Record<string, unknown>;
		if (configFile.endsWith('.json')) {
			const parsed: unknown = JSON.parse(content);
			validateJSONShape(parsed, path.basename(configFile));
			rendered = parsed as Record<string, unknown>;
		} else {
		await materializeGeneratedFiles(configFile, content, executionWorkingDir, options.tfPath);
			const evaluator = evaluatorFor({
				terraformCommand: options.command,
				terraformCliArgs: options.args,
				tfPath: options.tfPath,
			});
			rendered = runtimeValueToPlain(await evaluator.evaluateRenderedConfig(configFile, content, executionWorkingDir)) as Record<string, unknown>;
		}
		await runHooks(rendered, 'before_hook', options.command, unitDir, executionWorkingDir);
		const result = spawnSync(executable, [options.command, ...options.args], {
			cwd: unitDir,
			stdio: 'inherit',
			shell: false,
			env: {...process.env, ...inputVariables(rendered.inputs)}
		});
		if (result.error) throw new Error(`Unable to execute ${options.tfPath}: ${result.error.message}`);
		if (result.signal) throw new Error(`${options.tfPath} terminated by ${result.signal}`);
		if ((result.status ?? 1) !== 0) {
			try { await runHooks(rendered, 'error_hook', options.command, unitDir, executionWorkingDir); } catch (error) { console.error(error instanceof Error ? error.message : String(error)); }
			return result.status ?? 1;
		}
		await runHooks(rendered, 'after_hook', options.command, unitDir, executionWorkingDir);
	}
	return 0;
}

/**
 * The `inputs` block, as the variables OpenTofu reads.
 *
 * This is what `inputs` is FOR. Terragrunt evaluates the block and exports
 * each entry as `TF_VAR_<name>`, which is how a unit receives what its
 * configuration computed -- a dependency's outputs, a value from the plan, a
 * path derived from the workspace. Evaluating the block and then not passing
 * it meant every variable without a default was simply unset: OpenTofu
 * stopped and asked for it interactively, or refused.
 *
 * Non-string values are JSON, which is the encoding OpenTofu expects for a
 * `TF_VAR_` holding a list, a map or an object. A string is passed as itself:
 * JSON would wrap it in quotes that become part of the value.
 */
function inputVariables(inputs: unknown): Record<string, string> {
	if (inputs === null || typeof inputs !== 'object' || Array.isArray(inputs)) return {};
	const variables: Record<string, string> = {};
	for (const [name, value] of Object.entries(inputs as Record<string, unknown>)) {
		if (value === undefined) continue;
		variables[`TF_VAR_${name}`] = typeof value === 'string' ? value : JSON.stringify(value);
	}
	return variables;
}

async function collectFiles(root: string): Promise<string[]> {
	const info = await fs.stat(root);
	if (info.isFile()) return fileNames.has(path.basename(root)) ? [root] : [];
	const result: string[] = [];
	const entries = await fs.readdir(root, { withFileTypes: true });
	for (const entry of entries) {
		if (entry.name === '.git' || entry.name === '.terragrunt-cache' || entry.name === '.terragrunt-stack') continue;
		const target = path.join(root, entry.name);
		if (entry.isDirectory()) result.push(...await collectFiles(target));
		else if (entry.isFile() && fileNames.has(entry.name)) result.push(target);
	}
	return result.sort();
}

async function pathExists(target: string): Promise<boolean> {
	try {
		await fs.access(target);
		return true;
	} catch {
		return false;
	}
}

function offsetAt(content: string, line: number, character: number): number {
	const lines = content.split('\n');
	let offset = 0;
	for (let index = 0; index < line; index++) offset += Buffer.byteLength(lines[index] ?? '', 'utf8') + 1;
	return offset + Buffer.byteLength((lines[line] ?? '').slice(0, character), 'utf8');
}

function diagnostic(filename: string, content: string, item: any): DiagnosticOutput {
	const start = item.range?.start ?? { line: 0, character: 0 };
	const end = item.range?.end ?? start;
	const summary = item.message.startsWith('Unknown block') ? 'Unsupported block type' :
		item.message.startsWith('Unknown function') ? 'Call to unknown function' :
		item.message.startsWith('Unknown attribute') ? 'Unsupported attribute' :
		item.message.startsWith('Inline function') ? 'Invalid inline function' :
		(item.message.startsWith('Missing required argument') || item.message.startsWith('Missing required attribute')) ? 'Missing required argument' : 'HCL validation error';
	return {
		range: {
			filename,
			start: { line: start.line + 1, column: start.character + 1, byte: offsetAt(content, start.line, start.character) },
			end: { line: end.line + 1, column: end.character + 1, byte: offsetAt(content, end.line, end.character) }
		},
		summary,
		detail: item.message,
		severity: 'error'
	};
}

/**
 * Inline functions a configuration inherits through its includes. Resolving
 * includes evaluates the included files, which can fail for reasons unrelated to
 * inline functions — an unreadable parent, an unresolvable path. Those failures
 * are reported by the evaluation pass that follows, so here they simply yield no
 * inherited definitions rather than masking the real diagnostic.
 */
async function inheritedInlineFunctions(
	filePath: string,
	content: string,
	workDir: string
): Promise<Map<string, FunctionDefinition>> {
	const evaluator = evaluatorFor();
	try {
		return await evaluator.collectInheritedInlineFunctions(filePath, content, workDir);
	} catch {
		return new Map();
	}
}

async function validateFile(filePath: string, workDir: string, experiments: string[]): Promise<DiagnosticOutput[]> {
	const content = await fs.readFile(filePath, 'utf8');
	if (filePath.endsWith('.json')) {
		try { validateJSONShape(JSON.parse(content), path.basename(filePath)); return []; }
		catch (error) {
			return [{
				range: { filename: filePath, start: { line: 1, column: 1, byte: 0 }, end: { line: 1, column: 1, byte: 0 } },
				summary: 'HCL validation error', detail: error instanceof Error ? error.message : String(error), severity: 'error'
			}];
		}
	}
	const document = new ParsedDocument(new Workspace(), pathToFileURL(filePath).toString(), content);
	// Inline functions are inherited through includes, so a call to a function
	// declared in an included configuration is only resolvable once those
	// configurations have been read.
	if (document.hasIncludes()) {
		document.setInheritedInlineFunctions(await inheritedInlineFunctions(filePath, content, workDir));
	}
	const diagnostics = document.getDiagnostics().map(item => diagnostic(filePath, content, item));
	if (diagnostics.length > 0) return diagnostics;
	if (path.basename(filePath) === 'terragrunt.values.hcl') return [];
	// A unit that reads `dependency.<name>.outputs` cannot be evaluated without
	// them, and validation evaluates the unit. Terragrunt resolves them here
	// too: pointed at a workspace whose dependency was not applied it reaches
	// into that directory and complains about what it finds there, which is
	// only possible if it went looking.
	const evaluator = evaluatorFor({experiments});
	const result = await evaluator.evaluateUnit(filePath, content, workDir);
	if (result.valid) return [];
	return [{
		range: { filename: filePath, start: { line: 1, column: 1, byte: 0 }, end: { line: 1, column: 1, byte: 0 } },
		summary: 'HCL validation error',
		detail: result.error ?? 'Configuration evaluation failed',
		severity: 'error'
	}];
}

async function dependencyOrderedFiles(files: string[]): Promise<string[]> {
	const byDirectory = new Map<string, string>();
	for (const file of files) byDirectory.set(path.dirname(await fs.realpath(file)), file);
	const dependencies = new Map<string, string[]>();
	for (const file of files) {
		if (file.endsWith('.json')) {
			dependencies.set(file, []);
			continue;
		}
		const content = await fs.readFile(file, 'utf8');
		const ast: any = parse(content, {grammarSource: file, tracer: {trace() {}}});
		const refs: string[] = [];
		const visit = async (node: any): Promise<void> => {
			if (node.type === 'block' && node.value === 'dependency') {
				const attribute = node.children?.find((child: any) => child.type === 'attribute' && child.value === 'config_path');
				const valueNode = attribute?.children?.find((child: any) => child.type !== 'attribute_identifier');
				if (!valueNode) throw new Error(`dependency in ${file} is missing config_path`);
				// The literal, not an evaluation of it: evaluating an expression
				// in this file re-enters evaluation of the unit, including the
				// `dependency.<name>.outputs` reference, and deadlocks on the
				// very thing being resolved.
				const literal = String(valueNode.value ?? '');
				if (!literal) throw new Error(`dependency config_path in ${file} must be a literal path`);
				const targetDir = path.resolve(path.dirname(file), literal);
				let resolvedDir: string;
				try {
					resolvedDir = await fs.realpath(targetDir);
				} catch {
					throw new Error(`dependency config_path in ${file} names a directory that does not exist: ${literal}`);
				}
				const targetFile = byDirectory.get(resolvedDir);
				// A dependency OUTSIDE the set being run is not an error. This
				// function orders the units of one run, and a unit that was
				// applied earlier is read from its state rather than ordered
				// alongside. Refusing here made every partial run impossible.
				if (targetFile) refs.push(targetFile);
			}
			for (const child of node.children ?? []) await visit(child);
		};
		await visit(ast);
		dependencies.set(file, refs);
	}
	const result: string[] = [];
	const visiting = new Set<string>();
	const visited = new Set<string>();
	const visit = (file: string): void => {
		if (visiting.has(file)) throw new Error(`Dependency cycle detected at ${file}`);
		if (visited.has(file)) return;
		visiting.add(file);
		for (const dependency of dependencies.get(file) ?? []) visit(dependency);
		visiting.delete(file);
		visited.add(file);
		result.push(file);
	};
	for (const file of files.sort()) visit(file);
	return result;
}

async function runHooks(rendered: Record<string, unknown>, hookName: 'before_hook' | 'after_hook' | 'error_hook', command: string, unitDir: string, workDir: string): Promise<void> {
	const terraform = rendered.terraform;
	if (terraform === null || typeof terraform !== 'object' || Array.isArray(terraform)) return;
	const hooks = (terraform as Record<string, unknown>)[hookName];
	if (hooks === null || typeof hooks !== 'object' || Array.isArray(hooks)) return;
	for (const entry of Object.values(hooks as Record<string, unknown>)) {
		if (entry === null || typeof entry !== 'object' || Array.isArray(entry)) throw new Error(`${hookName} entries must be objects`);
		const hook = entry as Record<string, unknown>;
		const commands = hook.commands;
		if (!Array.isArray(commands) || !commands.every(item => typeof item === 'string')) throw new Error(`${hookName}.commands must be a list of strings`);
		if (!(commands as string[]).includes(command)) continue;
		if (hook.if !== undefined && hook.if !== true) continue;
		const execute = hook.execute;
		if (!Array.isArray(execute) || execute.length === 0 || !execute.every(item => typeof item === 'string')) throw new Error(`${hookName}.execute must be a non-empty list of strings`);
		const requestedDir = typeof hook.working_dir === 'string' ? path.resolve(unitDir, hook.working_dir) : unitDir;
		const configuredDir = path.join(await fs.realpath(path.dirname(requestedDir)), path.basename(requestedDir));
		const root = await fs.realpath(workDir);
		const relative = path.relative(root, configuredDir);
		if (relative === '..' || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) throw new Error(`${hookName}.working_dir is outside the working directory`);
		const result = spawnSync(String(execute[0]), (execute as string[]).slice(1), {cwd: configuredDir, stdio: 'inherit', shell: false});
		if (result.error) throw new Error(`Unable to execute ${hookName}: ${result.error.message}`);
		if ((result.status ?? 1) !== 0) throw new Error(`${hookName} exited with status ${result.status ?? 1}`);
	}
}

/**
 * Records every `--allow-path` and returns the arguments without them.
 *
 * Both spellings, because a path is the kind of argument people write with an
 * equals sign, and a flag that silently worked one way would be reported as
 * the boundary refusing a directory that had been permitted.
 */
function consumeAllowPaths(argv: string[]): string[] {
	const remaining: string[] = [];
	for (let index = 0; index < argv.length; index++) {
		const argument = argv[index];
		if (argument === '--allow-path') {
			const value = argv[++index];
			if (!value) throw new Error('--allow-path requires a path');
			allowedPaths.push(path.resolve(value));
			continue;
		}
		if (argument.startsWith('--allow-path=')) {
			const value = argument.slice('--allow-path='.length);
			if (!value) throw new Error('--allow-path requires a path');
			allowedPaths.push(path.resolve(value));
			continue;
		}
		remaining.push(argument);
	}
	return remaining;
}

async function main(argv: string[]): Promise<number> {
	// Taken out before anything dispatches on argv[0], because it is a GLOBAL
	// flag: every command below reads a configuration, and each one parses its
	// own arguments afterwards. Left in place it would make `tghclp
	// --allow-path DIR init` look like a command named "--allow-path".
	argv = consumeAllowPaths(argv);
	if (argv[0] === '--version' || argv[0] === '-v') {
		const versionFile = path.resolve(path.dirname(process.argv[1] ?? process.cwd()), '../version.txt');
		try { process.stdout.write(`${(await fs.readFile(versionFile, 'utf8')).trim()}\n`); }
		catch { throw new Error('Unable to determine tghclp version'); }
		return 0;
	}
	if (argv[0] === 'hcl' && (argv[1] === 'format' || argv[1] === 'fmt')) return formatHCL(argv.slice(2));
	if (argv[0] === 'stack' && argv[1] === 'generate') return stackGenerate(argv.slice(2));
	if (argv[0] === 'stack' && (argv[1] === 'run' || argv[1] === 'output' || argv[1] === 'clean')) return stackLifecycle(argv[1], argv.slice(2));
	if (argv[0] === 'scaffold') return scaffoldLocal(argv.slice(1));
	if (argv[0] === 'catalog') return catalogJSONL(argv.slice(1));
	if (argv[0] === 'backend') return backendCommand(argv.slice(1));
	if (argv[0] === 'render') return renderConfig(argv.slice(1));
	if (argv[0] === 'run') {
		if (argv.includes('--help')) {
			console.log(executionUsage());
			return 0;
		}
		return executeTerraformCommand(argv.slice(1));
	}
	if (tofuShortcuts.has(argv[0] ?? '')) return executeTerraformCommand(argv);
	if (argv[0] === 'exec') {
		const command = argv[1];
		if (!command || command.startsWith('-')) throw new Error('Usage: tghclp exec <command> [arguments...]');
		const result = spawnSync(command, argv.slice(2), {cwd: process.cwd(), stdio: 'inherit', shell: false});
		if (result.error) throw new Error(`Unable to execute ${command}: ${result.error.message}`);
		return result.status ?? 1;
	}
	if (argv[0] === 'find' || argv[0] === 'fd' || argv[0] === 'list' || argv[0] === 'ls') {
		const command = argv[0] === 'find' || argv[0] === 'fd' ? 'find' : 'list';
		const parsed = parseArgs(argv.slice(1));
		if (parsed === 'help') { console.log(discoveryUsage(command)); return 0; }
		if (parsed.dependencies && parsed.format !== 'dot') throw new Error('--dependencies is only supported with --format=dot');
		const roots = parsed.paths.length > 0 ? parsed.paths.map(target => path.resolve(parsed.workingDir, target)) : [parsed.workingDir];
		const configs = (await Promise.all(roots.map(root => discoverConfigs(root, parsed.noHidden, parsed.workingDir)))).flat().sort((a, b) => a.path.localeCompare(b.path) || a.type.localeCompare(b.type));
		if (configs.length === 0) throw new Error(`No Terragrunt configurations found under ${parsed.workingDir}`);
		if (command === 'find') printFind(configs, parsed);
		else if (parsed.dependencies && parsed.format === 'dot') await printDependencyGraph(parsed.workingDir);
		else printList(configs, parsed);
		return 0;
	}
	if (argv[0] === 'dag') {
		if (argv[1] !== 'graph') throw new Error('Usage: tghclp dag graph [options]');
		const parsed = parseArgs(argv.slice(2));
		if (parsed === 'help') { console.log(discoveryUsage('dag graph')); return 0; }
		if (parsed.dependencies && parsed.format && parsed.format !== 'dot') throw new Error('--dependencies is only supported with DOT output');
		await printDependencyGraph(parsed.workingDir);
		return 0;
	}
	if (argv[0] === 'info') {
		const parsed = parseArgs(argv.slice(2));
		if (parsed === 'help') { console.log('Usage: tghclp info print [options]'); return 0; }
		printInfo(argv[1] ?? '', parsed.workingDir);
		return 0;
	}
	if (argv[0] !== 'hcl' || argv[1] !== 'validate') throw new Error('Unsupported command; use "tghclp hcl validate", "find", "list", "dag graph", or "info print"');
	const parsed = parseArgs(argv.slice(2));
	if (parsed === 'help') { console.log(usage()); return 0; }
	const roots = parsed.paths.length > 0 ? parsed.paths.map(target => path.resolve(parsed.workingDir, target)) : [parsed.workingDir];
	const files = (await Promise.all(roots.map(collectFiles))).flat().sort();
	if (files.length === 0) throw new Error(`No Terragrunt HCL files found under ${parsed.workingDir}`);
	const diagnostics = (await Promise.all(files.map(file => validateFile(file, parsed.workingDir, parsed.experiments)))).flat();
	if (parsed.showConfigPath) {
		if (diagnostics.length > 0) {
			const paths = [...new Set(diagnostics.map(item => item.range.filename))];
			if (parsed.json) process.stdout.write(`${JSON.stringify(paths)}\n`);
			else for (const file of paths) process.stdout.write(`${file}\n`);
		}
	} else if (parsed.json) {
		if (diagnostics.length > 0) process.stdout.write(`${JSON.stringify(diagnostics)}\n`);
	} else if (diagnostics.length > 0) {
		for (const item of diagnostics) process.stderr.write(`${item.range.filename}: ${item.summary}: ${item.detail}\n`);
	}
	return diagnostics.length === 0 ? 0 : 1;
}

/**
 * Whether this file was run as a program, rather than imported as a library.
 *
 * Compared by RESOLVED PATH, because the name a program is invoked under is
 * not its filename. `npm install -g` links `bin/tghclp` at this file, so
 * `process.argv[1]` is that path -- and a check for a filename ending in
 * `/cli.js` was false for every globally installed copy. The command exited 0,
 * printed nothing, and did nothing, which is the worst way for this to fail:
 * it looks like a program with no output rather than one that never started.
 *
 * `realpath` on both sides resolves the symlink npm creates. It is compared
 * against `__filename` where that exists (the CJS build) and against the
 * module URL otherwise (ESM), so the same source serves both outputs.
 */
const invokedAsCLI = ((): boolean => {
	const entry = process.argv[1];
	if (!entry) return false;
	// The built file, whatever it is called on disk.
	if (/[/\\]cli\.(?:js|cjs|ts)$/u.test(entry)) return true;
	// A bin link npm made. Resolving it lands back on this file; comparing the
	// resolved paths is what makes the check independent of the name.
	try {
		const resolved = fsSync.realpathSync(entry);
		return /[/\\]cli\.(?:js|cjs|ts)$/u.test(resolved);
	} catch {
		return false;
	}
})();
if (invokedAsCLI) {
	try {
		if (process.argv.includes('--help') && process.argv.length <= 3) console.log(rootUsage());
		else main(process.argv.slice(2)).then(code => { process.exitCode = code; }).catch(error => { console.error(error instanceof Error ? error.message : String(error)); process.exitCode = 1; });
	} catch (error) {
		console.error(error instanceof Error ? error.message : String(error));
		process.exitCode = 1;
	}
}
